### ISSUE TITLE
🐞: [JUnit5] Suite view : Epic is not included in the tree, and tests are included twiced.

### ISSUE THREAD

**Issue by harmin-parra** [allure-framework/allure-java#1004]
### What happened?

I have the following JUnit5 test

```
@Test
public void fill_in_form() {
    Allure.epic("Epic");
    Allure.story("Story");
    Allure.suite("Suite");
    Allure.feature("Feature");
    // rest of code
```

When I run the test and generate the test, I get this behavior:

**Suite** view:
- Tests are included twice
- **Epic** label is not included in the tree

**Behavior** view:
- **Epic** is included in the tree
- **Feature** appears above **Story**. Shouldn't be the other way ? **Story** above, then **Feature** below ?

My understanding is that **Epic** and **Suite** should appear in the **Suite** view, whereas **Story** and **Feature** should appear in the **Behavior** view.

![image](https://github.com/allure-framework/allure-java/assets/16239820/b875ec40-bc18-41dd-98b0-03565ec1343b)

![image](https://github.com/allure-framework/allure-java/assets/16239820/c2c67f8c-df3f-48e3-8d4d-ec05ab419840)

### What Allure Integration are you using?

allure-junit5

### What version of Allure Integration you are using?

2.25.0

Note: 2.26.0 isn't present in Maven repo

### What version of Allure Report you are using?

2.25.0

Note: 2.26.0 isn't present in Maven repo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
The suites tab shows tests grouped by `parentSuite`, `suite` and `subSuite`. The behaviour tab shows tests grouped by `epic`, `feature`, and `story`. 

Some of the labels are set by default. For example, the framework usually sets' suite' for unit test frameworks, while `feature` and `story` are set by BDD frameworks (e.g., cucumber).
