### ISSUE TITLE
🐞: Allure TestOps selective runs doesn't work with TestNG + maven

### ISSUE THREAD

**Issue by dismoralzor** [allure-framework/allure-java#1023]
### What happened?

When I run one test from Allure TestOps, all tests are run in Jenkins job, the selective test execution is not working.

### What Allure Integration are you using?

allure-testng

### What version of Allure Integration you are using?

2.26.0

### What version of Allure Report you are using?

2.26.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cheshi-mantu** [comment]
@dismoralzor please follow the community rules and use English only

**Comment by dismoralzor** [comment]
@cheshi-mantu Oh, sorry sir, this is my first ticket

**Comment by cheshi-mantu** [comment]
I tried to generate projects from https://allurereport.org/start/ on 2.26.0 for testng and junit5
Junit5 selective test run works fine
[java17-junit5-maven.zip](https://github.com/allure-framework/allure-java/files/14770792/java17-junit5-maven.zip)

TestNG selective test run is not working
[java17-testng-maven.zip](https://github.com/allure-framework/allure-java/files/14770796/java17-testng-maven.zip)

**Comment by komissarov-qa-auto** [comment]
@baev 
Please fix this bug, my team is blocked by this feature (15 peoples)
Can your name the deadline for fixing?

**Comment by slevenet** [comment]
@komissarov-qa-auto Hi, we are going to fix it in the nearest time, until 20h of June

**Comment by vbragin** [comment]
@dismoralzor @komissarov-qa-auto 
What allure-testops-jenkins plugin version have you use?

**Comment by vbragin** [comment]
The problem was in jenkins plugin. Will be fixed in the next release.

**Comment by komissarov-qa-auto** [comment]
> The problem was in jenkins plugin. Will be fixed in the next release.

What are the deadlines? we really need this functional

As I understand it, information from our side is not needed, you have been provided with it

**Comment by dismoralzor** [comment]
Hello! 
sir, Is the problem solved for allurectl too? 

> @dismoralzor @komissarov-qa-auto What allure-testops-jenkins plugin version have you use?

allure-testops-jenkins plugin version 3.29.0
allurectl 2.15.1

> Could you add the following command into your job config and provide an output from it?

```
```
It says that a test plan has been created, but there is no ALLURE_TESTPLAN_PATH variable.

**Comment by vbragin** [comment]
@komissarov-qa-auto 
Try to use 4.0.2 from https://dl.qameta.io/ui/native/bin/allure-testops-jenkins
