### ISSUE TITLE
🐞: java junit4 selective test run is not working

### ISSUE THREAD

**Issue by cheshi-mantu** [allure-framework/allure-java#1024]
### What happened?

# Steps
1. Open https://allurereport.org/start/
2. Generate project for Java 17, JUnit4, maven
3. open poject
4. update allure libs version to 2.26.0
5. run tests once as `mvn clean test`
6. create testplan.json based on created test cases data (I used `allurectl job-run plan`)
7. delete all tests except one from testplan.json
8. exec `export ALLURE_TESTPLAN_PATH=testplan.json`
9. run `mvn clean test` or `mvnw clean test`

## AR 

all tests in the project are executed 

## ER

only tests mentioned in testplan.json are executed

## Project files

project generated via https://allurereport.org/start/

[junit4-maven-java17.zip](https://github.com/allure-framework/allure-java/files/14774014/junit4-maven-java17.zip)

### What Allure Integration are you using?

allure-junit4

### What version of Allure Integration you are using?

2.26.0

### What version of Allure Report you are using?

using allure testops

## Realtes to 

https://github.com/allure-framework/allure-java/issues/975

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
Allure start isn't yet updated. You need to include `allure-junit4-aspect` dependency for test plans to work
