### ISSUE TITLE
🐞: appending date and time stamp to the allure report generated working in windows but not working in Mac 

### ISSUE THREAD

**Issue by Karthik450G** [allure-framework/allure-java#1034]
### What happened?

The script I am using for generating the allure report is "generate:results": "allure generate --single-file allure-results -o allure-report\\Cypress-TestResults_%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%_%TIME:~0,2%-%TIME:~3,2%-%TIME:~6,2%.html 

### What Allure Integration are you using?

allure-cucumber3-jvm

### What version of Allure Integration you are using?

2.27

### What version of Allure Report you are using?

2.27

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
This is not related to Allure. You're using windows specific functions
