### ISSUE TITLE
Test Running Halted When There are Test Cases Failed in the Karate Framework

### ISSUE THREAD

**Issue by ewangtns** [allure-framework/allure-java#1040]
### Describe the Bug

I used the Allure-Karate and Allure-Maven to build my karate project and to generate allure report.

When I run "mvn clean test" in my local, it will run well and generate the allure report if there are no test cases failed. But if I have failed test cases in my test suites, it will keep running forever and won't terminate.

### Steps to Reproduce

1. Add plugins Allure-Karate and  Allure-Maven in the pom file.
2. `mvn test -Dkarate.options="classpath:path/to/your/feature.feature"` - run a specific feature file
3. If there is a failed test case in the feature file, it will halt (keep running forever) and won't finish running.

### Expected Behaviour

Although we have failed test cases in the test suite, we still can finish running and generate the allure report.

### What Language are you using?

Java

### What Framework/Allure Integration you are using?

allure-karate

### What version of Allure Integration you are using?

2.27.0

### What version of Allure Report you are using?

2.14.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
Could you please provide a sample project (GitHub repo) to reproduce the problem?

**Comment by Shyam3004** [comment]
I am facing the same issue!

**Comment by fromeroc9** [comment]
> ¿Podrías proporcionar un proyecto de muestra (repositorio de GitHub) para reproducir el problema?


Hello, I am currently having the same problem when it is for a parallel process, I share my code with you, you only need to change the test status to 200 for the reported incident to occur.

https://github.com/fromeroc9/karate-allure-reports

**Comment by baev** [comment]
@fromeroc9 thanks, it helped a lot!

see https://github.com/allure-framework/allure-java/pull/1065
