### ISSUE TITLE
Got totally blank allure report with Allure2+Gradle+Junit5

### ISSUE THREAD

**Issue by ozakharova** [allure-framework/allure-java#105]
## The allure2 report is generated but it is blank. 

My build.gradle looks like: 
    
    `apply plugin: 'java'
     apply plugin: 'idea'
     apply plugin: 'org.junit.platform.gradle.plugin'
     apply plugin: 'io.qameta.allure'
     
     defaultTasks 'clean', 'test'
    
    compileTestJava {
     sourceCompatibility = 1.8
     targetCompatibility = 1.8
     options.encoding = 'UTF-8'
     options.compilerArgs += "-parameters"
    }
    
    compileJava.options.encoding = 'UTF-8'
    
    tasks.withType(JavaCompile) {
     options.encoding = 'UTF-8'
    }
    
    repositories {
     mavenCentral()
    }
    
    buildscript {
     repositories {
         mavenCentral()
         maven {
             url "https://plugins.gradle.org/m2/"
         }
     }
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M5'
        classpath 'io.qameta.allure:allure-gradle:2.3'
     }
    }
    
    allure {
     aspectjweaver = true
     version = '2.1.1'
    }
    
    configurations {
     agent
    }
    
    junitPlatform {
	reportsDir file('build/allure-results ')
	platformVersion = "1.0.0-M5"
      filters {
         engines {
              include 'junit-jupiter'
          }
         includeClassNamePattern '.*Test'
      }
      enableStandardTestTask = true
    }
    
    dependencies {
     // JUnit5
     compile("org.junit.jupiter:junit-jupiter-api:5.0.0-M5")
     compile("org.junit.jupiter:junit-jupiter-engine:5.0.0-M5")
     compile ("org.junit.platform:junit-platform-console:1.0.0-M5")
    
    // Selenide
    compile("com.codeborne:selenide:4.4.3") {
        exclude group: 'junit'
    }
    
    // Allure
    agent "org.aspectj:aspectjweaver:1.8.10"
    compile "ru.yandex.qatools.allure:allure-junit-adaptor:1.4.23"
    compile "io.qameta.allure:allure-junit5:2.0-BETA15"
    }

    tasks.withType(JavaExec) {
     if (it.name == 'junitPlatformTest') {
         doFirst {
            jvmArgs "-javaagent:${configurations.agent.singleFile}"
         }
    
        finalizedBy 'allureReport'
     }
    }
`
I use command from IDEA Terminal to run tests:
> gradle clean test

Following tasks were performed.

> Task :jUnitPlatformTest

> Task :allureReport

Tests are finished successfully.  The allure report was generated with message: 
Report successfully generated to C:\IdeaProjects\CardTest\build\reports\allure-report

I opened this report but it is blank. I attached picture of my report. 

My test class:

    `package ru.creditcard;
    
    import static com.codeborne.selenide.WebDriverRunner.url;
    import static org.junit.jupiter.api.Assertions.assertTrue;
    
    import org.junit.jupiter.api.Test;
    import ru.creditcard.basetest.BaseTest;
    import ru.creditcard.page.BasicInformationPageAllure;
    import ru.yandex.qatools.allure.annotations.Title;
    
    @Title("Проверяем страницу с основной информацией")
    public class AllureTest extends BaseTest {
    
    @Test
    @Title("Проверяем переход на страницу паспортных данных")
    public void test1() {
     new BasicInformationPageAllure().openPage()
         .setName("TestName")
         .setSurname("TestSurname")
         .setMiddleName("TestMiddleName")
    
     url().contains("/anketa");
     assertTrue(1 == 1);
    }
    }`

Here is a part of TEST-junit-jupiter.xml:

    `<testcase name="test1()" classname="ru.creditcard.AllureTest" time="97.317">
    <system-out><![CDATA[
    unique-id: [engine:junit-jupiter]/[class:ru.creditcard.AllureTest]/[method:test1()]
    display-name: test1()
    ]]></system-out>
    </testcase>
    <testcase name="verifyExamplePage2()" classname="ru.creditcard.HomePageTest" time="0">`
    `<skipped><![CDATA[void ru.creditcard.HomePageTest.verifyExamplePage2() is @Disabled]]>`
    `</skipped>`
   `<system-out><![CDATA[`
    `unique-id: [engine:junit-jupiter]/[class:ru.creditcard.HomePageTest]/[method:verifyExamplePage2()]
    display-name: Some example2 name displayed will be here
    ]]></system-out>
    </testcase>
    <testcase name="verifyExamplePage()" classname="ru.creditcard.HomePageTest" time="0">`
    `<skipped><![CDATA[void ru.creditcard.HomePageTest.verifyExamplePage() is @Disabled]]>`
    `</skipped>`
    `<system-out><![CDATA[
    unique-id: [engine:junit-jupiter]/[class:ru.creditcard.HomePageTest]/[method:verifyExamplePage()]
    display-name: Some example name displayed will be here
    ]]></system-out>
    </testcase>
    <testcase name="verifyHappyPass()" classname="ru.creditcard.ShortProfilePageTest" time="0">`
    `<skipped><![CDATA[void ru.creditcard.ShortProfilePageTest.verifyHappyPass() is @Disabled]]>`
    `</skipped>`
    `<system-out><![CDATA[
    unique-id: [engine:junit-jupiter]/[class:ru.creditcard.ShortProfilePageTest]/[method:verifyHappyPass()]
    display-name: verifyHappyPass()
    ]]></system-out>
    </testcase>
    <system-out><![CDATA[
    unique-id: [engine:junit-jupiter]
    display-name: JUnit Jupiter
    ]]></system-out>
    </testsuite>
`

What could the problem be? Mayby I fogot some plugin or run annotation? I ran out of ideas. 

![report](https://user-images.githubusercontent.com/25900069/28117869-b8c2ac84-6717-11e7-87c5-3b535fe5e5f5.jpg)

**Comment by ehborisov** [comment]
Hi,

Gradle plugin does not support Junit5 yet.

Please use our gitter room to get help https://gitter.im/allure-framework/allure-ru

**Comment by baev** [comment]
you can find the working example of JUnit5 + Gradle + Allure here https://github.com/allure-framework/allure-java/blob/master/examples/junit5/build.gradle
