### ISSUE TITLE
🐞: [JUnit5][Maven][Kotlin][Selenide] When retry the test, no testCaseId is generated for the successfully completed test

### ISSUE THREAD

**Issue by mrVorotnichok** [allure-framework/allure-java#1056]
### What happened?

The problem is as follows:
There is a test run in which the tests failed with an error. Next, the failed tests are restarted as part of the same launch.
If the test was successfully completed after the restart, then the testCaseId was not generated for it in *-result.json. There is a duplication of test cases, one with the status Passed, the other with the status Failed/Broken

### What Allure Integration are you using?

allure-junit5

### What version of Allure Integration you are using?

2.24.0

### What version of Allure Report you are using?

2.24.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
Please provide a sample repo to reproduce the problem

**Comment by mrVorotnichok** [comment]
> Please provide a sample repo to reproduce the problem

due to the nda policy, I cannot provide the repository, maybe selective information will suit?
 For example, part of the pom file

**Comment by baev** [comment]
You can use this https://github.com/allure-examples/junit5-kotlin-maven example as a template, fork and try to modify it so the issue reproduces.

**Comment by mrVorotnichok** [comment]
Thanks, I'll try and come back.
