### ISSUE TITLE
[TestNg] Wrong coding in report when description on cyrillic words

### ISSUE THREAD

**Issue by magnus80** [allure-framework/allure-java#106]
1. write description on Russian
![2017-07-12_18-19-21](https://user-images.githubusercontent.com/17245384/28125258-bccb6ae8-672e-11e7-8a5b-b310fda9f6e9.png)
2. run test
3. open allure Serve
![2017-07-12_18-21-14](https://user-images.githubusercontent.com/17245384/28125336-fd0dd636-672e-11e7-8b24-bc0b62f0af33.png)

**Comment by magnus80** [comment]
| Allure version | 2.2.1 |
| --- | --- |
| Test framework | testng@6.11 |
| Allure integration | allure-testng@2.0-BETA14 |

**Comment by baev** [comment]
@magnus80 can't reproduce the problem. Please, make sure you have `UTF-8` encoding specified for your project. Also you can provide an example to reproduce the problem, link it here, then feel free to reopen the issue

**Comment by FoX31** [comment]
I have same problem, but in bumboo. When I start the local report everything is all right.
![4](https://user-images.githubusercontent.com/22095151/32771988-90cdf262-c935-11e7-81c7-7c99d00f4777.PNG)
![214](https://user-images.githubusercontent.com/22095151/32772005-9860d990-c935-11e7-8fc6-5656c699ce25.PNG)
