### ISSUE TITLE
[TestNg] Set Up/Tear down sections collect and display information from all tests

### ISSUE THREAD

**Issue by IZaiarnyi** [allure-framework/allure-java#107]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
 Set Up/Tear down sections collect and display information from all tests

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Str:

1. 

```
public class BaseTest {
    @BeforeClass(alwaysRun = true)
    public static void start() {
        System.out.println("start");
    }

    @AfterClass(alwaysRun = true)
    public static void finish() {
        System.out.println("finish");
    }
}
```
2.

```
public class Tests extends BaseTest {
    @BeforeClass
    public static void init() {
        System.out.println("init");
    }

    @Test
    public void tests(){
        System.out.println("test1");
    }
}
```

3.

```
public class Tests2 extends BaseTest {
    @BeforeClass
    public static void init() {
        System.out.println("init");
    }

    @Test
    public void test2(){
        System.out.println("test2");
    }
}
```

4. Run xml configuration

```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
<suite name="Complex suite" configfailurepolicy="continue" preserve-order="true" verbose="1" parallel="classes" thread-count="5" >
    <test name="All tests">
        <classes>
            <class name="Tests" />
            <class name="Tests2" />
        </classes>
    </test>
</suite>
```

![setupsection](https://user-images.githubusercontent.com/8190742/28213613-864f743c-68af-11e7-9d29-48a746198e5d.png)
![teardownsection](https://user-images.githubusercontent.com/8190742/28213617-893f3f60-68af-11e7-887b-f8d7de8ffec1.png)

#### What is the expected behavior?
Set Up/Tear down sections should contain only related to the test information 

![setupsection](https://user-images.githubusercontent.com/8190742/28213696-e3d09fe6-68af-11e7-8812-4570cc6665ff.png)

![teardownsection](https://user-images.githubusercontent.com/8190742/28213698-e5b87996-68af-11e7-83d0-75c0c116bd2c.png)

#### What is the motivation / use case for changing the behavior?
Right now It's very confusing and weird realization that doesn't give you useful information.

#### Please tell us about your environment:

| Allure version | 2.2.1 |
| --- | --- |
| Test framework | testng@6.10|
| Allure integration | allure-testng@2.0-BETA15 |
| Generate report using | allure-commandline |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
duplicate #99 , fixed in #100 , will be available in next release
