### ISSUE TITLE
Attachments not working when combined with JUnit Timeout rule

### ISSUE THREAD

**Issue by aiannucci** [allure-framework/allure-java#108]
Bug report

Attachments are not working after adding JUnit Timeout rule to the test case. The attachments are not getting properly linked in the corresponding JSON files.
This is one of the official JUnit rules, and it is a common use case to add this rule to set timeout, specially in Abstract classes.
To reproduce the issue, please check the code [here](https://github.com/aiannucci/allure-junit-example/commit/e9435effece7288db1fa652c53572deefc417782)

| Allure version | 2.2.1 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure integration | allure-junit4@2.0-BETA15 |
| Generate report using | allure-maven@2.8 |

**Comment by aiannucci** [comment]
Any progress on this one? Any chance to get it included in the next beta release?
Thanks!

**Comment by baev** [comment]
I already have a fix for that issue in https://github.com/allure-framework/allure-java/tree/rft-lifecycle/ , but there is more work are required (need to update all the integrations, improve test coverage and support model changes in report). The fix will be available as soon as possible, ETA ~ 4 weeks

**Comment by aiannucci** [comment]
hi @baev, do you have any renewed estimates for this fix? I know it was waiting for some more changes in other pieces of the framework. Is there any way I can help?
Thanks!

**Comment by alexKazarin** [comment]
Hi! Have same problem as "**[TestNG] Test timeout property discards Test body steps** #113". Still no news?
