### ISSUE TITLE
🐞: Broken/Skipped testStage in the middle of scenario is not failing test case - overall score is PASSED

### ISSUE THREAD

**Issue by MSlaski** [allure-framework/allure-java#1100]
### What happened?

Java Test Project with Serenity BDD 4.1.20 (Cucumber 7, Selenium 4, Appium 2, Rest-Assured 5)
Some tests are marked with status **PASSED** even if in the scenario some testStage will be BROKEN or SKIPPED
For some reason explicit call of `fail()` method (doesn't care if Im using JUnit or AssertJ) which is throwing `AssertionError` is not stopping the tests. On next step test is failing due to timeout of `WebElement` visibility.

Please check:
7 Test Cases marked as **PASSED** where the last one really failed
![Screenshot 2024-07-15 at 16 28 36](https://github.com/user-attachments/assets/29ec29fa-de21-4e78-b46d-efb37f52f93f)

Timeout appeared on 5th Step where rest of the steps were marked as PASSED BUT without details about the sub steps etc
![Screenshot 2024-07-15 at 16 29 32](https://github.com/user-attachments/assets/7e4ed60d-9511-4e6e-9fbb-6f24530fc130)

Steps details of working test case:
![Screenshot 2024-07-15 at 16 30 32](https://github.com/user-attachments/assets/f1988375-653e-4d98-b45d-eb7a4dd8aa28)

And the testStages of 5th step:
![Screenshot 2024-07-15 at 16 31 33](https://github.com/user-attachments/assets/ece02c4f-d7e5-4260-8867-4fa725ef4626)

I didn't hide two methods names, cuz they are the same (called on different classes but both annotated with `@Step`) - perhaps its worth to mention that

I tried to reproduce the issue on smaller project but without a luck, unfortunately can't provide a test code of my project

### What Allure Integration are you using?

allure-awaitility, allure-cucumber7-jvm, allure-junit4, allure-rest-assured

### What version of Allure Integration you are using?

2.28.0

### What version of Allure Report you are using?

2.28.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MSlaski** [comment]
perhaps not an issue with Allure - Cucumber is returning status PASSED for such step

**Comment by baev** [comment]
@MSlaski Allure alwaysrespectst the status returned by the test framework, so if cucumber is returning the passed, it should be passed in the report (so all works as expected on our side)
