### ISSUE TITLE
🐞: restore support of scala 2.12 & 2.13 for allure-scalatest

### ISSUE THREAD

**Issue by atais** [allure-framework/allure-java#1104]
### What happened?

I think https://github.com/allure-framework/allure-java/pull/433 removed 2.12 from being published:
https://mvnrepository.com/artifact/io.qameta.allure/allure-scalatest
last 2.12 version is 2.13.2
 
and from 2.13.10 https://mvnrepository.com/artifact/io.qameta.allure/allure-scalatest/2.13.10 \
scala version is defaulting to 2.13 without the suffix, which is even worse :(

Could we please add 2.12 and 2.13 suffixes and deploy all missing 2.12 versions?

### What Allure Integration are you using?

allure-scalatest

### What version of Allure Integration you are using?

2.13.2

### What version of Allure Report you are using?

2.13.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
I managed to release 2.28.1 with `allure-scalatest` cross-compiled for Scala 2.12 and 2.13. It should become available on Maven Central within an hour.

**Comment by atais** [comment]
I can see the release but 2.28.1 is missing on maven central for 17 hrs now.
Could you please check if it was published correctly?

**Comment by baev** [comment]
mvnreposioty updates its indexes with a considerable delay. All the artifacts are available for download:

https://repo.maven.apache.org/maven2/io/qameta/allure/
https://repo.maven.apache.org/maven2/io/qameta/allure/allure-scalatest_2.12/2.28.1/
https://repo.maven.apache.org/maven2/io/qameta/allure/allure-scalatest_2.13/2.28.1/
