### ISSUE TITLE
[TestNG] Test timeout property discards Test body steps

### ISSUE THREAD

**Issue by ASaunin** [allure-framework/allure-java#113]
#### I'm submitting a ... 
  - [X] bug report

#### What is the current behavior?
Timeout limitation clears steps inside the test body section.
You can check it in existing `allure2-testng-report` code example, by adding `timeOut = 1000` section:
```
    @Issue("21")
    @Feature("Authorization")
    @Story("ALR-23")
    @TmsLink("24")
    @Owner("sskorol")
    @Severity(SeverityLevel.CRITICAL)
    @Test(dataProvider = "getData", description = "Login with a valid user credentials", timeOut = 1000)
    public void loginWithRegisteredUser(final User user) {
        open(LoginPage.class)
                .loginWith(user);
    }
```
#### Actual behavior (without `timeOut = 1000` property):
![image](https://user-images.githubusercontent.com/19559375/28367299-0aedbcb6-6c99-11e7-85dc-afcedcf0fc15.png)

#### Wrong behavior (when `timeOut = 1000` property is present):
![image](https://user-images.githubusercontent.com/19559375/28367414-879206fa-6c99-11e7-87e9-f9b3ac970153.png)

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.11 |
| Allure integration | allure-testng@2.0-BETA15 |
| Generate report using | allure-maven@2.18 |

**Comment by baev** [comment]
duplicate https://github.com/allure-framework/allure-java/issues/108 . That is a bug, will be fixed ASAP
