### ISSUE TITLE
NPE on nullable objects in assertions

### ISSUE THREAD

**Issue by sskorol** [allure-framework/allure-java#115]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When passing nullable object to `assertThat`, AssertJ aspect throws NPE.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
```java
    @Test
    public void shouldHandleNullableObject() {
        assertThat((Object) null).as("Nullable object").isNull();
    }
```

#### What is the expected behavior?
AsserJ aspect should correctly handle nullable objects.

#### What is the motivation / use case for changing the behavior?
Pretty common assertion scenario.

#### Please tell us about your environment:

| Allure version | 2.2.1 |
| --- | --- |
| Test framework | junit/testng |
| Allure integration | allure-assertj@2.0-BETA16 |

#### Other information 
Will create a PR with a fix shortly.

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by eroshenkoam** [comment]
@sskorol 👍
