### ISSUE TITLE
currentStepContext in AllureStorage is empty

### ISSUE THREAD

**Issue by mqzry** [allure-framework/allure-java#122]
#### I'm submitting a ... 
  - [x] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
I have a method with @Step annotation. This will go through the StepAspect and try to `getLifecycle().startStep(uuid, result);` (StepAspects.java). But this method call does nothing because `storage.getCurrentStep().value == null`.  This happens because the storage is Threadlocal.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
I do not know if this is a bug or something that is not supported.
Reproducible situation for me : 

- Have parallel=methods
- Have @beforeMethod in base test class A
- Have @Step method and @Test in class B that extends A

#### What is the expected behavior?
That AllureLifecycle.startStep works even though AllureLifecycle.startTestCase happened on another thread.

#### What is the motivation / use case for changing the behavior?
To have support for @Step functionality

#### Please tell us about your environment:

| Allure version | 2.0-BETA16 |
| Test framework | testng@6.8.8|
| Allure integration | allure-testng@2.0-BETA16 |
| Generate report using | allure-maven@2.8 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by mqzry** [comment]
What is the status of this ? @baev 

You said in august in https://github.com/allure-framework/allure-java/pull/126 that it would take 4 weeks.

**Comment by baev** [comment]
should be fixed in upcoming 2.8.0 release.
