### ISSUE TITLE
Flaky annotation being ignored and not showing on report

### ISSUE THREAD

**Issue by aiannucci** [allure-framework/allure-java#127]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Flaky annotation not working in JUnit4

#### What is the expected behavior?

Tests marked as flaky should show up in the report as such when they fail.

#### What is the motivation / use case for changing the behavior?

Feature has not been implemented yet for JUnit4

#### Please tell us about your environment:

| Allure version | 2.3.1 |
| --- | --- |
| Test framework | junit@4.12 |
| Allure integration | allure-junit4@2.0-BETA16 |
| Generate report using | allure-maven@2.8 |

**Comment by SporeTec** [comment]
Any update or workarround for this issue?
