### ISSUE TITLE
[allure-cucumber-jvm] cannot write .json report files for features and scenarios with / in description

### ISSUE THREAD

**Issue by letsrokk** [allure-framework/allure-java#130]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

If Feature description or Scenario name has '/' in name, Allure formatter cannot save report .json file

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Example Feature:
```
Feature: FEATURE/with slash in description

  Scenario: With / in name
    Given feature or scenario has / in description
    When running tests
    Then report.json is not saved
```

Demo project with example features and scenarios
https://github.com/letsrokk/allure-cucumber-example

#### What is the expected behavior?

Report files should be saved

#### What is the motivation / use case for changing the behavior?

Fix bug :)

#### Please tell us about your environment:

| Allure version | 2.3.1 |
| --- | --- |
| Test framework | testng@6.9.10 |
| Allure integration | allure-cucumber-jvm@2.0-BETA16 |
| Generate report using | allure-commandline@2.3.1 |

#### Other information 

```
io.qameta.allure.AllureResultsWriteException: Could not write Allure test result`
java.nio.file.NoSuchFileException: allure-results/feature/with-slash-in-description;with-/-in-name-result.json
```
```
$ mvn clean test
$ ls target/allure-results/
feature---without-slash-in-description;without-slash-in-name-result.json				
step-with-@step-annotation;scenario-which-makes-call-to-method-with-@step-annotation-result.json
```

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by 8M00M8** [comment]
Also ":" character fails.

**Comment by baev** [comment]
should be fixed by now
