### ISSUE TITLE
annotation @Parameter is missing

### ISSUE THREAD

**Issue by tnimni** [allure-framework/allure-java#136]
Hi,

I been using allure 1 until now, I'm trying to migrate to allure 2, how ever I heaviely use the @Parmeter annotation, and seems to be missing in allure 2

Is this by design or was overlooked?

If it is by design, what should I replace it with?

Thanks

**Comment by tnimni** [comment]
@baev I noticed you added this part in allure 1, any chance you can help us out here as well?

**Comment by sskorol** [comment]
@tnimni you can use [allure-java-migration](https://mvnrepository.com/artifact/io.qameta.allure/allure-java-migration) module, which allows working with old annotations.

**Comment by tnimni** [comment]
@sskorol thank you, i'll have a look :)
