### ISSUE TITLE
Dynamically setting @TmsLink, @DisplayName & @Issue with DataProvider data

### ISSUE THREAD

**Issue by symonk** [allure-framework/allure-java#156]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
template.

#### What is the current behavior?
I cannot seem to figure out a way in order to set the Issue, TmsLink and display name programmatically from the @Test method, I have tried overriding the value(s) at runtime but with no success, my report does not seem to include the data

#### What is the motivation / use case for changing the behavior?
When using the junit @DataProvider annotation and passing data from a 2D array, we can then set our Issue/TmsLink/DisplayNames in the array test data and the report would reflect such data.

My sincerest apologies if this is possible to do already, I am struggling to find a way to make it work effectively

| Allure version | 2.2.0 |
| --- | --- |
| Test framework |junit 4.12 |
| Allure adaptor | allure-junit4@2.0-BETA13 |
| Generate report using | allure-maven@2.19 |

#### Other information 
When annotating the method with the @Issue("foo"), all tests of the data provider will be set with this IssueId

**Note:** Sorry i logged this issue in the wrong project, please close close the issue here:
https://github.com/allure-framework/allure2/issues/645

**Comment by symonk** [comment]
I am able to achieve this by implementing Issue and overriding the value() at runtime, is there a simpler more readable/friendly means of doing so? if not this is something I feel has real benefit in adding

**Comment by symonk** [comment]
we can implement Issue/DisplayName/TmsLink in our own class, then using the java reflection API check for the test method at runtime and override the values for these annotations but we must set the as blank on the test method, my solution works but its very hacky and really unclean, is there a better way guys?

**Comment by baev** [comment]
Did you tried `Allure.getLifecycle()` API?

Also you can use

https://github.com/allure-framework/allure-java/blob/master/allure-java-commons/src/main/java/io/qameta/allure/Allure.java#L39-L41

and

https://github.com/allure-framework/allure-java/blob/master/allure-java-commons/src/main/java/io/qameta/allure/util/ResultsUtils.java#L131-L137

**Comment by Juvat** [comment]
@baev that will do the trick. Thanks a lot!

**Comment by dhruvvinayak** [comment]
@Juvat, can you please share the code snippet you implemented using Allure.getLifecycle() API?

**Comment by GregoryGum** [comment]
I am using following code to dynamicly change DisplayName at run time:
		AllureLifecycle oLifecycle = Allure.getLifecycle();
		oLifecycle.updateTestCase(testResult -> testResult.setName("My DisplayName"));

**Comment by vlad230** [comment]
I'm struggling to get it work but it's not working for me.

I am using this approach: https://www.swtestacademy.com/change-test-name-testng-dataprovider/

Instead of the Extent report part I'm using this to updated the allure report test case name but it's not working with the latest Allure version 2.20.1:
`public class TestListener extends ApiBaseTest implements ITestListener {

    @Override
    public void onTestStart(ITestResult result) {
        log.info("Executing test method: {} from test class: {}", result.getName(), result.getTestClass().getName());

        //update test method name in Allure report
        Allure.getLifecycle().updateTestCase(testResult -> testResult.setName(result.getName()));
    }
.....
`

Any ideas @baev & @GregoryGum ? What am I doing wrong?
