### ISSUE TITLE
Attachements adding not working in Allure-Jbehave.

### ISSUE THREAD

**Issue by aKumpan** [allure-framework/allure-java#157]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [+] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Allure.addAttachment("My attachment", "My attachment content"); call not working when called from steps. Attachment can be created, but it is not attached to resulting JSON file and to report accordingly.

getLifecycle().updateStep(attachment -> attachment.withAttachments(new Attachment().withName("test"))); - Not working also.

getLifecycle().updateTestCase(uuid, attachment -> testResult..withAttachments(new Attachment().withName("test"))); - is only working one, when called with valid uuid of the test. 
(can be tested inside before/afterScenario in io.qameta.allure.jbehave.AllureJbehave).
But this uuid is not accessible anywhere in the steps.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Described in https://github.com/aKumpan/allure-java/tree/allure-jbehave-attachements-issue
Commit link: https://github.com/aKumpan/allure-java/commit/7f0be7714b0698ae8cfe044ad155e15fbf2d11a7

#### What is the expected behavior?
Expected possibility to add attachments for running scenario/step when using Jbehave.
For now, it is only possible to do inside io.qameta.allure.jbehave.AllureJbehave methods. 
(E.g. calling         getLifecycle().updateTestCase(uuid, attachment -> attachment.withAttachments(new Attachment().withName("test")));
inside before/afterScenario with current test uuid). Which is not accessible for client side.

#### What is the motivation / use case for changing the behavior?
Adding attachments for test results.

#### Please tell us about your environment:
Latest master branch for allure-java (allure-jbehave)

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

It may be caused because of getLifecycle().getCurrentTestCase(); is always Optional.Empty when called from steps.

**Comment by aKumpan** [comment]
Problem fixed. Screenshoots successfully adding for single thread run.
Describing fix for multithread:
When you run jBehave - org.jbehave.core.reporters.ConcurrentStoryReporter is used. 
There are code, which delays stepProcessing in multiThreading run.
![image](https://user-images.githubusercontent.com/11076815/38460670-927d5eea-3a8c-11e8-87fb-c6a0f34bc04c.png)

To attach screenshots in multithread run (for Jbehave), you need to save screenshot in method annotated with
 @AfterScenario(uponOutcome = AfterScenario.Outcome.FAILURE), it is not delayed. In this method you need to access uuid of current scenario and save screenshot in Map ThreadLocal<Map<String, Byte[]>> (uuid, screenshot).

Then, in AllureJbehave, you need to do something like that:
![image](https://user-images.githubusercontent.com/11076815/38460714-6ae1d0cc-3a8d-11e8-8dc4-39a1557771c2.png)

You are reading screenshots from your map, and adding it as attachment.
So when Jbehave will call org.jbehave.core.reporters.ConcurrentStoryReporter#failed() - you can access your previously saved screenshot.



Because of delayed stepProcessing in multiThreading run, you might also find that timing in your reports is not correct - that issue cannot be fixed from allure standpoint, it is caused by Jbehave step processing in multithread run.

**Comment by baev** [comment]
should be fixed by now
