### ISSUE TITLE
[TestNG][Maven] Error: Directory ".../target/allure-results" not found message when running `$ mvn test allure:report`

### ISSUE THREAD

**Issue by romanik-roma** [allure-framework/allure-java#160]
#### I'm submitting a ... 
  - [ x] bug report

#### What is the current behavior?
Running the command
`$ mvn test`
generates the allure results into './allure-results' folder, not into './target/allure-results' folder.

In according with [13.6.2 Results directory](https://docs.qameta.io/allure/latest/#_maven_4) section of the documentation, it is said that `This path can be relative from the build directory (for maven it is the target directory)`. However, now the 'allure-results' folder is not in the 'target' folder.

As a consequence, the command
`$ mvn allure:report`
generates the following error:
[ERROR] Directory E:\workspace\project_name\target\allure-results not found.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
The sample code to reproduce the issue can be found [here](https://github.com/romanik-roma/allure2_results_dir_location)

Run the command:
`$ mvn clean test`
and find that the `allure-results` folder is located not in the `target` folder, but in the root folder of the project.

Then run the command:
`$ mvn allure:report`
and observe the error in the command line of type
```
[ERROR] Directory E:\workspace\project_name\target\allure-results not found.
```

#### What is the expected behavior?
After running `$ mvn test`, allure results should be generated into './target/allure-results' folder, as described in [3.6.2 Maven Configuration Results directory](https://docs.qameta.io/allure/latest/#_maven_4) section of the documentation.

After running `$ mvn allure:report`, the report should be generated into './target/site/allure-maven/index.html', as described in [13.6.3 Maven Usage](https://docs.qameta.io/allure/latest/#_maven_4) section of the documentation, 
as well as on the GitHub page of the [Allure Maven Plugin](https://github.com/allure-framework/allure-maven).

#### What is the motivation / use case for changing the behavior?
It would be great to run one command:
`$ mvn clean test allure:report`
and obtain the test run report.

However, at the moment, one needs to run first `$ mvn test`, and then either invoke allure command line tool on the generated allure-results folder, or copy the results into target folder and only then to run `$ mvn allure:report`.

And the second motivation is that the current behaviour does not correspond to the documentation.

#### Please tell us about your environment:

| Allure version | 2.4.1 |
| --- | --- |
| Test framework | testng@6.11 |
| Allure integration | allure-testng@2.0-BETA19 |
| Generate report using | allure-maven@2.9 |

#### Other information 
Sample `pom.xml` file

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.qa</groupId>
	<artifactId>allure_results_folder_inconsistency</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<aspectj.version>1.8.11</aspectj.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.20.1</version>
				<configuration>
					<argLine>
						-javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar
					</argLine>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.aspectj</groupId>
						<artifactId>aspectjweaver</artifactId>
						<version>${aspectj.version}</version>
					</dependency>
				</dependencies>
			</plugin>

			<plugin>
				<groupId>io.qameta.allure</groupId>
				<artifactId>allure-maven</artifactId>
				<version>2.9</version>
				<configuration>
					<reportVersion>2.4.1</reportVersion>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.11</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-testng</artifactId>
			<version>2.0-BETA19</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjweaver</artifactId>
			<version>${aspectj.version}</version>
		</dependency>

	</dependencies>
</project>
```

**Comment by romanik-roma** [comment]
I've done some investigation, and maybe found the places of interest in the source code.

In Allure 2, in [AllureLifecycle.java](https://github.com/allure-framework/allure-java/blob/ebb1a42b90eaa93bc00c6e116c15871165c9646a/allure-java-commons/src/main/java/io/qameta/allure/AllureLifecycle.java), the last method reads
```
private static FileSystemResultsWriter getDefaultWriter() {
        final Properties properties = PropertiesUtils.loadAllureProperties();
        final String path = properties.getProperty("allure.results.directory", "allure-results");
        return new FileSystemResultsWriter(Paths.get(path));
    }
```
so I may assume it is the place where 'allure-results' folder is selected as the location for results.
And that's why the results are placed in `./allure-results` folder.

On the other hand, in allure 1, in [AllureConfig.java](https://github.com/allure-framework/allure1/blob/07878a9c1726c5527635ed8a21ebead20f6c4aaf/allure-model/src/main/java/ru/yandex/qatools/allure/config/AllureConfig.java) there is the following constant:
```
protected static final File DEFAULT_RESULTS_DIRECTORY = new File("target/allure-results");
```
which is then used in 
```
    @Property("allure.results.directory")
    protected File resultsDirectory = DEFAULT_RESULTS_DIRECTORY;
```
so that's is why in Allure 1, the results are placed in `./target/allure-results` directory.

**Comment by baev** [comment]
you need to create `allure.properties` file in your resources folder and specify the results directory (see https://github.com/allure-examples/allure-testng-example/blob/master/src/test/resources/allure.properties)

**Comment by romanik-roma** [comment]
Thanks, @baev 
It works the way you recommended.

Does this mean that the [documentation](https://docs.qameta.io/allure/latest/) is still not up to date with Allure 2?
For example, 
in [Section 13.6 Maven](https://docs.qameta.io/allure/latest/#_maven_4) the example of issue pattern is still in Allure 1 format
```
<plugin>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-maven</artifactId>
    <configuration>
       <properties>
           <allure.issues.tracker.pattern>http://example.com/%s</allure.issues.tracker.pattern>
       </properties>
    </configuration>
</plugin>
```
while in `allure.properties` file the pattern and property name is different
`allure.link.issue.pattern=https://example.org/issue/{}`

**Comment by baev** [comment]
@romanik-roma yeah, feel free to send us a pull request with fixes to https://github.com/allure-framework/allure-docs

**Comment by RomanIovlev** [comment]
I've just somehow automatically allure-results generated into root folder and allure:serve search for target/allure-results
I try to add 
                <configuration>
                    <properties>
                        <allure.results.directory>allure-results</allure.results.directory>
                    </properties>
                </configuration>
in allure maven plugin in pom
and allure properties in src/test/resources
allure.results.directory=allure-results

But still got 
[ERROR] Directory ...\target\allure-results not found.
[WARNING] Allure report was skipped because there is no results directories found. 

What i'm doing wrong?
Here the link to project
I just do:
> clean install
> run allure:serve
(I won't put folder name in command line)

**Comment by nickmsix** [comment]
I have absolutely the same problem as @RomanIovlev 
Is there any solution?

**Comment by benyue1978** [comment]
> 

Took me some time to figure it out.
You have to configure allure.properties first.

> allure.results.directory=target/allure-results

Then you run a new test, the result will be in the target directory.

> mvn clean test
> mvn allure:serve

**Comment by virennitkkr** [comment]
I scanned the configuration, i found you have missed two things.

1. **Add listner in testng.xml file.**
 <listeners>
        <listener class-name="io.qameta.allure.testng.AllureTestNg"/>
    </listeners>
 2. **Add dependency in pom.xml file**
 <dependency>
          <groupId>io.qameta.allure</groupId>
          <artifactId>allure-testng</artifactId>
          <version>2.13.9</version>
          <scope>test</scope>
      </dependency>
**Run test cases:** 
mvn clean test
mvn allure:serve
