### ISSUE TITLE
Step is removed from storage before listener execution

### ISSUE THREAD

**Issue by sskorol** [allure-framework/allure-java#177]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Unable to set attachment in `beforeStepStop`. It doesn't appear in test results report.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
```java
public class StepListener implements StepLifecycleListener {

    @Override
    public void beforeStepStop(final StepResult result) {
        addAttachment("Log", "text content");
    }
}
```

#### What is the expected behavior?
Attachment specified in `beforeStepStop` is linked to the step.

#### What is the motivation / use case for changing the behavior?
Users are not able to use `beforeStepStop` event to perform attachments.

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | testng@6.13.1 |
| Allure integration | allure-testng@2.0-BETA21 |
| Generate report using | allure-gradle@2.5 |

**Comment by Savostytskyi** [comment]
Have the same issue. Does it work for other allure/testNg versions?
