### ISSUE TITLE
Allure ignore '@DisplayName' annotation for test class for junit 5

### ISSUE THREAD

**Issue by rosolko** [allure-framework/allure-java#180]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Display text from '@DisplayName' annotation only for test methods.
And ignore for test class.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
```
@DisplayName("Sample test class")
class SampleTests {
    @Test
    @DisplayName("Sample test #2")
    void test2() {
    }

    @Test
    @DisplayName("Sample test #1")
    void test1() {
    }
}
```

#### What is the expected behavior?
Display text from '@DisplayName' annotation for test class in report.
`Sample test class`

#### What is the motivation / use case for changing the behavior?
Display package name instead of text from '@DisplayName' annotation

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | junit@5.0.2 |
| Allure integration | allure-junit5@2.0-BETA21 |
| Generate report using | allure-gradle@2.5 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

<img width="874" alt="screen shot 2018-01-03 at 11 58 42" src="https://user-images.githubusercontent.com/11458319/34514265-ac246180-f07d-11e7-97c8-e2672c424adc.png">

**Comment by symonk** [comment]
> DisplayName
> @DisplayName annotation has been removed.

can you try @Description("Sample Test #1")

Just guessing at a quick glance, I will look into it if that is not the case soon

**Comment by rosolko** [comment]
@symonk `@DisplayName` - it's annotation from junit 5, not from allure

**Comment by symonk** [comment]
my apologies @rosolko I completely misread

**Comment by velios** [comment]
Please do smth with this behavior. Or maybe allure already had some description functionality to classes? I tried but it didn't work
