### ISSUE TITLE
Parse steps into human-readable format

### ISSUE THREAD

**Issue by ZhyliaievD** [allure-framework/allure-java#186]
#### I'm submitting a ... 
  - [x] feature request
  - [ ] bug report
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Method name is used to display steps in the report if `@Step` has default value

#### What is the expected behavior?
If `@Step` doesn't have value specified - method name is parsed in human-readable format: camelCase is split into words

#### What is the motivation / use case for changing the behavior?
Make it easier for a human to read steps 

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure integration | allure-testng@2.0-BETA21 |
| Generate report using | Jenkins Allure Plugin@2.25.1/ allure-maven@2.9|

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by uterator** [comment]
Hi, according to the spec https://docs.qameta.io/allure/#_steps this request should have been already implemented but seems it is not working. if so, this ticket is mostly a bug rather than a feature request. I think it was correctly working on Allure 1.

**Comment by baev** [comment]
Since version 2.0 human readable step name format feature was removed

> Hi, according to the spec https://docs.qameta.io/allure/#_steps this request should have been already implemented but seems it is not working.

note removed via https://github.com/allure-framework/allure-docs/pull/105

**Comment by ZhyliaievD** [comment]
This feature request is based on this comment from @eroshenkoam:
https://automated-testing.info/t/allure2-i-human-readable-format-stepov/18523/2
Which doesn't look like it was going to be removed

**Comment by baev** [comment]
@ZhyliaievD we are going to add support of this at some day but at the moment feature is not implemented.
