### ISSUE TITLE
Wrong allure results directory with gradle default config.

### ISSUE THREAD

**Issue by rosolko** [allure-framework/allure-java#204]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

Allure place results in **project_root/allure-results** instead of **project_root/build/allure-results** folders.
Also this behavior reproduce for _gradle composite builds_ if root and dependent projects depend from allure.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

My *build.gradle* file with allure config:
```
plugins {
    id 'io.qameta.allure' version '2.5'
}

ext {
    junitJupiterVersion = '5.0.1'
    allureVersion = '2.0-BETA22'
}

allure {
    autoconfigure = false
    version = '2.5.0'
}

dependencies {
    implementation("io.qameta.allure:allure-okhttp3:$allureVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitJupiterVersion")
    testRuntimeOnly("io.qameta.allure:allure-junit5:$allureVersion")
}

wrapper.gradleVersion = '4.5'
```

#### What is the expected behavior?

Place all results to **project_root/build/allure-results** folder.

#### What is the motivation / use case for changing the behavior?

Config by default should works well.

#### Please tell us about your environment:

| Allure version | 2.5.0 |
| --- | --- |
| Test framework | junit@5.0.1 |
| Allure integration | allure-junit5@2.0-BETA22 |
| Generate report using | allure-gradle@2.5.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by dimencionrider** [comment]
got the same issue. I still don't know how to fix it.

**Comment by rosolko** [comment]
@dimencionrider There is only one workaround for this issue - pass `allure.results.directory` property via task argument `-Dallure.results.directory=<target>` or create `allure.properties` file with `allure.results.directory` field.

**Comment by baev** [comment]
By default allure adaptors stores results into `<work-dir>/allure-results` folder. There is two different ways to override the defaults:

* using `allure.properties` placed in resources (recommended way). 
* using related system properties. System properties will override configuration specified in properties file.

We can make that `allure-gradle` will add system property that will override default results directory to `build/allure-results` folder, but this will override user configuration provided via `allure.properties` file. Also I'd like to keep the behaviour the same for all the users (Gradle users that configures dependencies manually without using Allure Gradle plugin and Maven users)

**Comment by baev** [comment]
An example of `allure.properties` file: https://github.com/allure-examples/allure-testng-example/blob/master/src/test/resources/allure.properties
