### ISSUE TITLE
Exception on processing AssertJ SoftAssertions

### ISSUE THREAD

**Issue by ostrovanka** [allure-framework/allure-java#210]
#### I'm submitting a ... 
  - [+ ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Build fails with exception:
```
java.lang.BootstrapMethodError-->call site initialization exception
org.assertj.core.internal.cglib.core.CodeGenerationException: java.lang.BootstrapMethodError-->call site initialization exception
```
if there SoftAssertions class is used in test:
```
 SoftAssertions soft=new SoftAssertions();
      soft.  assertThat(25).as("Test description").isEqualTo(26);
```
#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1.Apply allure-assertJ plugin version 2.6.0
2.Create any tst with usage of SoftAssertions classs
3.Run tests

#### What is the expected behavior?
There is not exceptions (except assertion failures) in build. Allure report with allure-assertj plugin is generated

#### Please tell us about your environment:
| Allure version | 2.6.0 |
| AssertJ plugin | allure-assertj:2.6.0 |
| Test framework | testng@6.8 |
| Allure integration | allure-testng@2.6.0 |
| Generate report using | allure-gradle@2.5 |

**Comment by spaluchowski** [comment]
Is there any progress on this?

**Comment by baev** [comment]
I added tests for this case and everything works as expected. Feel free to reopen issue if problem still occurs, but make sure you provided a sample project (as repository on Github) that reproduces the problem
