### ISSUE TITLE
-Dcucumber.options in <argline> of the maven surefire plugin throws error

### ISSUE THREAD

**Issue by VenkataKoripalli** [allure-framework/allure-java#211]
I have the following configurations and pom file in my project.

When I do the "mvn test" I am getting the following error:
Please refer to /Users/vkorip/Downloads/CucumberJVMExamples-master 2/cucumberjvm-selenium-page-object/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd "/Users/vkorip/Downloads/CucumberJVMExamples-master 2/cucumberjvm-selenium-page-object" && /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/bin/java -javaagent:/Users/vkorip/.m2/repository/org/aspectj/aspectjweaver/1.8.10/aspectjweaver-1.8.10.jar ' 

If I remove the "-Dcucumber.options="--plugin ru.yandex.qatools.allure.cucumberjvm.AllureReporter" from <argline> of the surefire plugin the tests are working fine.

Please help
Thank you in advance

**Versions**
Java Version: 8
Maven: 3.5.2

**POM FILE:**
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>testing</groupId>
	<artifactId>selenium</artifactId>
	<version>0.0.1</version>
	<packaging>jar</packaging>
	<name>Selenium</name>
	<properties>
		<cucumber.version>1.2.0</cucumber.version>
		<picocontainer.version>2.15</picocontainer.version>
		<path.chrome>drivers\chromedriver.exe</path.chrome>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<aspectj.version>1.8.10</aspectj.version>
		<cucumber.version>1.2.5</cucumber.version>
		<allure.version>1.4.16</allure.version>
		<allure-cucumber.version>1.6.3</allure-cucumber.version>
		<allure-maven.version>2.8</allure-maven.version>
		<slf4j.version>1.7.21</slf4j.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-testng</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>${cucumber.version}</version>
		</dependency>
		<dependency>
			<groupId>com.codeborne</groupId>
			<artifactId>phantomjsdriver</artifactId>
			<version>1.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>2.44.0</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.11-beta3</version>
		</dependency>
		<dependency>
			<groupId>xml-apis</groupId>
			<artifactId>xml-apis</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>xerces</groupId>
			<artifactId>xercesImpl</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>ru.yandex.qatools.allure</groupId>
			<artifactId>allure-cucumber-jvm-adaptor</artifactId>
			<version>1.6.2</version>
		</dependency>

	</dependencies>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.20</version>
					<configuration>
						<systemPropertyVariables> <allure.results.directory>target/allure-results</allure.results.directory>
							<outputDirectory>target/allure-results</outputDirectory> </systemPropertyVariables>
						<argLine>
							-javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
							-Dcucumber.options="--plugin ru.yandex.qatools.allure.cucumberjvm.AllureReporter"
						</argLine>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.aspectj</groupId>
							<artifactId>aspectjweaver</artifactId>
							<version>${aspectj.version}</version>
						</dependency>
						<dependency>
							<groupId>org.apache.maven.surefire</groupId>
							<artifactId>surefire-junit47</artifactId>
							<version>2.18</version>
						</dependency>
					</dependencies>
				</plugin>

				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<configuration>
						<source>1.8</source>
						<target>1.8</target>
					</configuration>
				</plugin>

			</plugins>
		</pluginManagement>
	</build>

	<reporting>
		<excludeDefaults>true</excludeDefaults>
		<plugins>
			<plugin>
				<groupId>io.qameta.allure</groupId>
				<artifactId>allure-maven</artifactId>
				<version>${allure-maven.version}</version>
			</plugin>
		</plugins>
	</reporting>
</project>

**Comment by hyfzur** [comment]
@VenQA How did you resolve this ?
