### ISSUE TITLE
Cannot attach Selenide screenshot into allure 2.0 report

### ISSUE THREAD

**Issue by dimencionrider** [allure-framework/allure-java#215]
I want to attach a screenshot of my failed test into allure report.

I'm using:
 - java
 - gradle
 - selenide
 - allure 2.0
 - testNG

 
For better understanding, here is the tool, I'm working on: https://youtu.be/X9ubuj2k7bQ

Here is the path to selenide screenshots:
.../myProject/build/reports/tests/pic.png

Here is the path to allure-results folder:
.../myProject/target/allure-results/....testsuite.xml

Can someone help me to fix the issue, or provide the correct way of implementation?

Conclusion:
I would like to have at the end - run the command "allure serve .../myProject/target/allure-results/"
and screenshots should be shown under my failed tests allure report section.

Thanks,
Roman

**Comment by baev** [comment]
Allure knows nothing about screenshots from Selenide, so you need to save screenshots using Allure API.

Also you can consider using Allure Selenide integration, that will do all the work for you https://docs.qameta.io/allure/#_selenide

**Comment by dimencionrider** [comment]
Selenide listener does not work for me. It cannot download sources from maven repository.

import io.qameta.allure.selenide.AllureSelenide; - showing red colour in my IDEA

any other ways? or workarounds?

**Comment by baev** [comment]
hm https://repo.maven.apache.org/maven2/io/qameta/allure/allure-selenide/2.6.0/

Have you added dependency? Try to invalidate caches for IDEA and restart

**Comment by rosolko** [comment]
@baev @dimencionrider Just not that 2.6.0 version can't configure screenshots and savePageSource properties because that was added after release.

**Comment by dimencionrider** [comment]
in my build.gradle file I have this dependency:

compile group: 'io.qameta.allure', name: 'allure-selenide', version: '2.0-BETA22'

here is screenshot of my method: https://prnt.sc/j1qc5e
I cannot import AllureSelenide()

**Comment by dimencionrider** [comment]
@baev @rosolko does not work with 2.6.0

**Comment by rosolko** [comment]
@janeberets It's weird. Because readme file updated with new features, but released the old one :(

**Comment by rosolko** [comment]
@baev Can you please release 2.6.1 or 2.7.0 version with latest selenide ext version?

**Comment by simple-elf** [comment]
@rosolko @dimencionrider @janeberets you can use 2.6.0 version. There is screenshots config value `true` by default
```
SelenideLogger.addListener("AllureSelenide", new AllureSelenide());
```

**Comment by symonk** [comment]
you can use the default as above which will include screenshots, or you can implement `LogEventListener` and pass the concrete implementation to SelenideLogger.addListener("foo", new concreteImpl());

allure will release soon i guess and make it simple to have the fluent capabilities.  Here is an example I implemented my own listener to include screenshot, page source and a .json log file per threaded test

https://github.com/symonk/Selenide-TestNG-Allure2-Framework/blob/master/gui-tests/src/test/java/io.github.symonk/configurations/selenide/CustomListener.java

**Comment by simple-elf** [comment]
@dimencionrider @rosolko 2.7.0 released - https://github.com/allure-framework/allure-java/releases/tag/2.7.0
So now you can write like in docs https://docs.qameta.io/allure/#_selenide
```
import io.qameta.allure.selenide.AllureSelenide;
...
SelenideLogger.addListener("AllureSelenide", new AllureSelenide().screenshots(true).savePageSource(false));
```

Also you can disable standart selenide screenshoots by `Configuration.screenshots = false` because it will just dublicates files.

@dimencionrider Do you have any other questions or problems? Can we close this issue?

**Comment by udenav** [comment]
@simple-elf 

Hello, I have the same problem, but I'm used maven instead gradle.

 I'm used `SelenideLogger.addListener("AllureSelenide", new AllureSelenide().screenshots(true))` and com.codeborne.selenide.testng.ScreenShooter. 
Screenshot was saved to path 
> build\reports\tests\com\<packafe_of_runned_test>\ClassTestName\testMethodName\1534421185337.0.png

But steel have no attachments in alure results

**Comment by amardeep2006** [comment]
I recently faced this issue with TestNG and could not resolve with
`SelenideLogger.addListener("AllureSelenide", new AllureSelenide().screenshots(true).savePageSource(true));`

Finally this worked for me (may not be the best solution ) but it may be helpful to someone who reach here via Search engine.

``` java   @Attachment(value = "Screenshot", type = "image/png")
    public byte[] captureScreenshot() throws IOException {
        // Generate a random filename using UUID
        String randomFileName = "screenshot-" + UUID.randomUUID().toString();
        Selenide.screenshot(randomFileName).getBytes(StandardCharsets.UTF_8);
        File screenshot = Screenshots.getLastScreenshot();
        return screenshot == null ? null : Files.toByteArray(screenshot);
    }
````
