### ISSUE TITLE
Android Instrumentation Support

### ISSUE THREAD

**Issue by mikeholler** [allure-framework/allure-java#226]
Hi there!

I just discovered your project, and was interested in whether there is support for Android Instrumentation tests (or what it would look like to add it). I found this issue over on the parent project:

https://github.com/allure-framework/allure1/issues/862

I searched for "android" in the issues here and didn't find anything.

**Comment by baev** [comment]
check out this project https://github.com/TinkoffCreditSystems/allure-android
