### ISSUE TITLE
Allure Junit5 2.6.0 doesn't support @Disabled annotation though in Release notes and in Master `executionSkipped` method is present

### ISSUE THREAD

**Issue by azakordonets** [allure-framework/allure-java#229]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
`allure-junit-platform` module has AllureJunit5 class, which in `master` has `executionSkipped` method. However, when i download the jar from maven - i don't see this method present `AllureJunit5`. 

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Add 
```
    compile (group: 'io.qameta.allure', name: 'allure-junit5', version: '2.6.0')
```
2. Navigate to `AllureJunit5` class inside the downloaded jar. 

#### What is the expected behavior?
`executionSkipped` method should be present

#### What is the motivation / use case for changing the behavior?
Without this method all Junit5 `@Disabled` tests are displayed as `Passed`, which is wrong.  

#### Please tell us about your environment:

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | junit@5.3.0-M1 |
| Allure integration | allure-junit@2.6.0|
| Generate report using | allure-gradle@2.5 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
fixed in 2.7.0
