### ISSUE TITLE
[feature request] Change color for retries tests on the graphs "retries trend"

### ISSUE THREAD

**Issue by programmingcourses** [allure-framework/allure-java#237]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
![joxi_screenshot_1532601947344](https://user-images.githubusercontent.com/8340885/43258625-a7a456e4-90fd-11e8-840a-24d8aa1408b9.png)

#### What is the expected behavior?
change collor #fffeca on hex - #72119cf0

**Comment by baev** [comment]
should be fixed via https://github.com/allure-framework/allure2/pull/847
