### ISSUE TITLE
Support when/then Spock annotations

### ISSUE THREAD

**Issue by tdurova** [allure-framework/allure-java#239]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure doesn't support when/then steps from Spock (bdd framework)

#### What is the expected behavior?
To see bdd steps from Spock specs in Allure reports

#### What is the motivation / use case for changing the behavior?
test analyst and manual QAs will able to see what happens in automation tests without reading full log with some technical information

#### Please tell us about your environment:
Jenkins+maven+java+geb+spock

| Allure version | 2.19.0 |
| --- | --- |
| Test framework | JUnit@4.12 |
| Allure integration | allure-spock@2.7.0 |
| Generate report using | allure-maven@2.9 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by rameshnatesan** [comment]
any update on this? please add this feature.

**Comment by havenqi** [comment]
wondering in which version we could see this fix? Furthermore, Furthermore, it'd be grateful to have more info regarding alure with spock framework in the guide.

**Comment by rameshnatesan** [comment]
this is the only missing feature that is most needed today by all Spock users. Please take this feature as a priority.

**Comment by rameshnatesan** [comment]
Happy new year 2019! I have a feeling that this feature will be done and available by end of this year!

**Comment by havenqi** [comment]
Oh... that sounds misable. Now we use both allure, and [spock report](https://github.com/renatoathaydes/spock-reports). Really hope allure can have spock annotation support integrated soon.
