### ISSUE TITLE
@Description annotation does not work on allure-junit-example project

### ISSUE THREAD

**Issue by oggboy** [allure-framework/allure-java#242]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  -  bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
I use allure-junit-example project, the default  allure-junit4 version is 2.0:
```
<dependency>
       <groupId>io.qameta.allure</groupId>
       <artifactId>allure-junit4</artifactId>
       <version>2.0-BETA13</version>
</dependency>
```
And this 2.0 version does not support the @Description annotation.
We should update this version to 2.7.0 now.

**Comment by baev** [comment]
@oggboy thanks, fixed
