### ISSUE TITLE
Weird steps tree in report for concurrent steps execution.

### ISSUE THREAD

**Issue by AnatolyPopov** [allure-framework/allure-java#246]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When I try to execute substeps of a step concurrently the tree of steps in test body description becomes weird. All the substeps executed concurrently look like substeps of each other in the tree or sometimes several substeps can disappear.

![weird example](https://user-images.githubusercontent.com/2312534/46361576-b6327200-c676-11e8-9a38-b68e0f3e09a7.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Here is an example of the code https://github.com/AnatolyPopov/junit5-allure-example

To reproduce the issue run

`mvn clean test allure:serve`

several times. Since the bug is floating sometimes it works as expected.

#### What is the expected behavior?
In expected report substeps executed concurrently should have the same parent in the tree.

![expected](https://user-images.githubusercontent.com/2312534/46361638-d2ceaa00-c676-11e8-95f6-2cb1c15d52bf.png)

#### What is the motivation / use case for changing the behavior?
Sometimes it's needed to handle several heavy but exactly the same things in the same test or step.
For example in my case I have several similar and independent components on a test page and I want to handle them concurrenlty to improve overall timings. 

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | Junit5@5.3.1 |
| Allure integration | allure-junit5@2.7.0 |
| Generate report using | allure-maven@2.9 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)
Here is a possible fix.
https://github.com/AnatolyPopov/allure-java/commit/70a857cb0eeb2b4883dc8379508c3a57757ce8f0

**Comment by baev** [comment]
Fixed in master

<img width="408" alt="screen shot 2018-10-30 at 20 22 11" src="https://user-images.githubusercontent.com/2149631/47737269-88dee100-dc81-11e8-974d-f1eb615bc5f2.png">

Next release planned by the end of this week
