### ISSUE TITLE
Allure Jenkin Report is not showing setup and tear down method

### ISSUE THREAD

**Issue by sbhatta2018** [allure-framework/allure-java#277]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
On executing 'allure serve' command from my system, the report shows setup and tear down method in the report. But if I execute it via Jenkins, it does not displays the setup and tear down in the 'Steps'

#### What is the expected behavior?
setup and tear down shown display in the 'Steps' irrespective of whether I execute it locally from Jenkins

#### Please tell us about your environment:

allure-testng - 2.7.0
testng - 6.14.3

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
This looks like configuration issue. 

* Check Allure Jenkins Plugin configuration. It should be configured to use last version of Allure Command line, results directories should be the same you are using locally
* Try to find command that Jenkins uses to run your tests. Try run this command locally and build the report

**Comment by sbhatta2018** [comment]
Yeah, but I am unable to resolve it. If I execute locally through Maven, everything is fine.

**Comment by baev** [comment]
probably because of https://github.com/allure-framework/allure-java/issues/219
Test fixtures are broken at the moment when running TestNG tests in parallel
