### ISSUE TITLE
Allure-junit-maven

### ISSUE THREAD

**Issue by raja3450** [allure-framework/allure-java#28]
hi ,
can anyone help me for generating allure reports with maven-junit framework.Is there any documentation regarding what are all the plugins to be added & sample example program to generate report. I used "https://github.com/allure-examples/allure-junit-example/blob/master/pom.xml#L44-L46" plugins  mentioned in this site and Im unable to use the @step annotation & report is also not generated.

**Comment by eroshenkoam** [comment]
Can you copy your pom.xml here?

**Comment by raja3450** [comment]
[Uploading POM.txt…]()

**Comment by raja3450** [comment]
[POM.txt](https://github.com/allure-framework/allure-java/files/824495/POM.txt)

**Comment by raja3450** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.plintron.com</groupId>
	<artifactId>Lyca_Myaccounts</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>Lyca_Myaccounts</name>
	<description>Lyca_Myaccounts</description>
	
	<properties>
    <jetty.http.port>9000</jetty.http.port>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <allure.version>1.4.24.RC3</allure.version>
    <aspectj.version>1.8.9</aspectj.version>
    <compiler.version>1.7</compiler.version>
</properties>

	<dependencies>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.0.1</version>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-java</artifactId>
			<version>1.2.4</version>
		</dependency>

		<dependency>
			<groupId>info.cukes</groupId>
			<artifactId>cucumber-junit</artifactId>
			<version>1.2.4</version>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		
		
		
<dependency>

			<groupId>com.relevantcodes</groupId>
			<artifactId>extentreports</artifactId>
			<version>2.41.2</version>
		</dependency>
		
		<dependency>
        <groupId>ru.yandex.qatools.allure</groupId>
        <artifactId>allure-junit-adaptor</artifactId>
        <version>1.5.2</version>
    </dependency> 
    <dependency>
        <groupId>com.googlecode.zohhak</groupId>
        <artifactId>zohhak</artifactId>
        <version>1.1.1</version>
        <scope>test</scope>
    </dependency>
    
    

    
    
</dependencies>



<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>2.19.1</version>
            
            <configuration>
   <propertiesFilePath>path/to/your/allure.properties</propertiesFilePath>
</configuration>
            <configuration>
                <argLine>
                    -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                </argLine>
                <properties>
                    <property>
                        <name>listener</name>
                        <value>ru.yandex.qatools.allure.junit.AllureRunListener</value>
                    </property>
                </properties>
            </configuration>
            <dependencies>
                <dependency>
                    <groupId>org.aspectj</groupId>
                    <artifactId>aspectjweaver</artifactId>
                    <version>1.9.0.BETA-5</version>
                </dependency>
                    <dependency>
    <groupId>org.aspectj</groupId>
    <artifactId>aspectjrt</artifactId>
    <version>1.9.0.BETA-5</version>
</dependency>

            </dependencies>
        </plugin>
        <plugin>
        <groupId>pentaho-kettle</groupId>
                    <artifactId>kettle-engine</artifactId>
                    <version>3.2.2</version>
        </plugin>
        <plugin>
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-maven-plugin</artifactId>
            <version>9.3.7.v20160115</version>
            <configuration>
                <webAppSourceDirectory>${project.build.directory}/site/allure-maven-plugin</webAppSourceDirectory>
                <httpConnector>
                    <port>${jetty.http.port}</port>
                </httpConnector>
                <stopKey>stop</stopKey>
                <stopPort>1234</stopPort>
            </configuration>
        </plugin>
    </plugins>
    </build>
 
<reporting>
    <excludeDefaults>true</excludeDefaults>
    <plugins>
        <plugin>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-maven-plugin</artifactId>
            <version>2.5</version>
        </plugin>
    </plugins>
</reporting>


   

</project>

**Comment by raja3450** [comment]
@eroshenkoam  i have attached POM.xml file above

**Comment by eroshenkoam** [comment]
Seems like your pom.xml is correct.
You just need to start your tests by: 
`mvn test`
and generate Allure report by 
`mvn site`
After that you need to make sure that following file exists: 
`target/site/allure-maven-plugin/index.html`

**Comment by raja3450** [comment]
@eroshenkoam 

while running test the below error is shown.

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Raji_Automation 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Raji_Automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Raji_Automation ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to D:\Maven\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /D:/Maven/src/main/java/Org/Automation/Calculator.java:[5,10] cannot find symbol
  symbol:   class Step
  location: class Org.Automation.Calculator
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.364 s
[INFO] Finished at: 2017-03-13T12:15:03+05:30
[INFO] Final Memory: 15M/35M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project Raji_Automation: Compilation failure
[ERROR] /D:/Maven/src/main/java/Org/Automation/Calculator.java:[5,10] cannot find symbol
[ERROR] symbol:   class Step
[ERROR] location: class Org.Automation.Calculator
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException


Can u tell me how to resolve this issue.

**Comment by eroshenkoam** [comment]
You have the compilation error here. 
Seems like you need to import Step annotation like here
https://github.com/allure-examples/allure-junit-example/blob/master/src/main/java/my/company/steps/WebDriverSteps.java#L10

**Comment by raja3450** [comment]
![annotation](https://cloud.githubusercontent.com/assets/26132939/23848064/5e1f9092-07fb-11e7-979b-6175f1e973f8.png)

After importing step annotation also error throw.I have attached screenshot for the same.plz check

**Comment by baev** [comment]
That seems to be not an Allure issue. Please use other resources such as Stackoverflow to get an information how to start java project/add dependencies and so on.
