### ISSUE TITLE
Screenshots not always attaching to report

### ISSUE THREAD

**Issue by jsa34** [allure-framework/allure-java#285]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Using allure-cucumber-jvm-3 with screenshots after each step and getting every so often so screenshots attached (suspect a race-condition issue). To get screenshots after each step, using custom class:

```
public class AllureScreenshotPublisher implements Formatter {
private final AllureLifecycle allureLifecycle;

public AllureScreenshotPublisher() {
    this.allureLifecycle = Allure.getLifecycle();
}

@Override
public void setEventPublisher(EventPublisher publisher) {
    publisher.registerHandlerFor(TestStepFinished.class, this::handleTestStepFinished);
}

private void handleTestStepFinished(final TestStepFinished event) {
    byte[] screenShot = ((TakesScreenshot) DriverManager.getDriver()).getScreenshotAs(OutputType.BYTES);
    allureLifecycle.addAttachment(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MMM-yy_hh:mm:ss")), "image/png", "png", screenShot);
}
}

```
and then define this as a plugin for each runner:

```
@CucumberOptions(
glue = {"*.stepdefs"},
features = {"target/parallel/features/[CUCABLE:FEATURE].feature"},
plugin = {"*.allure.AllureScreenshotPublisher",
"io.qameta.allure.cucumber3jvm.AllureCucumber3Jvm"}
)

public class [CUCABLE:RUNNER] extends AbstractTestNGCucumberTests {

}

```
Any ideas why this fails about 5-10% of the time?

Using:
<dependency>
<groupId>io.qameta.allure</groupId>
<artifactId>allure-cucumber3-jvm</artifactId>
<version>2.7.0</version>
</dependency>

and Selenium 3.141.59 (if it helps :) )

**Comment by baev** [comment]
@jsa34 does CucumberJVM guarantees formatters execution order? 

Also you can consider using `StepLifecycleListener#beforeStepStop` to add screenshots, that should help. 

PS StepLifecycleListener is configured via Java SPI

**Comment by jsa34** [comment]
Hello - 

Following your advice, I have now changed the implementation to be as follows:

Custom class for taking screenshots after each step:
```
public class AllureScreenshotPublisher implements StepLifecycleListener {
    private final AllureLifecycle allureLifecycle;

    public AllureScreenshotPublisher() {
        this.allureLifecycle = Allure.getLifecycle();
    }

    @Override
    public void beforeStepStop(final StepResult result) {
        byte[] screenShot = ((TakesScreenshot) DriverManager.getDriver()).getScreenshotAs(OutputType.BYTES);
        allureLifecycle.addAttachment(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MMM-yy_hh:mm:ss")), "image/png", "png", screenShot);
    }

}
```

I have removed the plugin from the runner classes:
```
@CucumberOptions(
glue = {"*.stepdefs"},
features = {"target/parallel/features/[CUCABLE:FEATURE].feature"},
plugin = {"io.qameta.allure.cucumber3jvm.AllureCucumber3Jvm"}
)

public class [CUCABLE:RUNNER] extends AbstractTestNGCucumberTests {

}
```

And placed in src/resources/META-INF/services a file called io.qameta.allure.listener.StepLifecycleListener with the contents:

`*****.allure.AllureScreenshotPublisher`
(Blanked out parent location, but this location is correct in the project.

Now when I run, I get no screenshots at all taken.  Am I missing something?

**Comment by baev** [comment]
@jsa34 just tested it out, works for me. Could you verify that `StepLifecycleListener` is loaded and executed? 

PS The only issue I'm aware so far is that people accidentally create `META-INF.services` directory instead of nested directories when using IDEA, because it looks identically

**Comment by jsa34** [comment]
You were absolutely right - META-INF.services was not META-INF/services.  Now this calls screenshots at the end of every step, but they do not attach to the report's steps.  I have had to add initialising Allure.getLifecycle() in the base test class as I don't call the plugin anymore and so the lifecycle doesn't get called otherwise.

I can see all the attachments in the allure-results directory but nothing in the attachments dir of allure report that is built.

(Updated runner class:

```
import io.qameta.allure.Allure;

import cucumber.api.CucumberOptions;
import cucumber.api.testng.AbstractTestNGCucumberTests;

@CucumberOptions(
        glue = {"*****.stepdefs"},
        features = {"target/parallel/features/[CUCABLE:FEATURE].feature"},
        plugin = {"io.qameta.allure.cucumber3jvm.AllureCucumber3Jvm"}
        )

public class [CUCABLE:RUNNER] extends AbstractTestNGCucumberTests {

    public [CUCABLE:RUNNER]() {
        Allure.getLifecycle();
    }

}
```

**Comment by baev** [comment]
@jsa34 hint: you can use `Allure.addAttachment` methods instead, that should help to get rid of additional `Allure.getLifecycle()` call in constructor. Or remove `allureLifecycle` caching from `AllureScreenshotPublisher` (directly call `Allure.getLifecycle().addAttachment(...)` inside `beforeStepStop` method)

**Comment by jsa34** [comment]
I have implemented your suggestion and still have the same results:

1.  Runner class:

```
@CucumberOptions(
        glue = {"*****.stepdefs"},
        features = {"target/parallel/features/[CUCABLE:FEATURE].feature"},
        plugin = {"io.qameta.allure.cucumber3jvm.AllureCucumber3Jvm"}
        )

public class [CUCABLE:RUNNER] extends AbstractTestNGCucumberTests {
}
```

2.  

public class AllureScreenshotPublisher implements StepLifecycleListener {
    
```
    @Override
    public void beforeStepStop(StepResult result) {
        byte[] screenShot = ((TakesScreenshot) DriverManager.getDriver()).getScreenshotAs(OutputType.BYTES);
        Allure.getLifecycle().addAttachment(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MMM-yy_hh:mm:ss")), "image/png", "png", screenShot);
    }
```
3.  Placed in src/resources/META-INF/services a file called io.qameta.allure.listener.StepLifecycleListener with the contents:
*****.allure.AllureScreenshotPublisher

RESULT:
And after the test run, I can see all the attachments in /target/allure-results, but when Jenkins builds the report after the test run, the /allure-report/data/attachments/ is empty.

**Comment by jsa34** [comment]
Thank you for your help, btw!  Much appreciated - I'm just at a loss :(

**Comment by baev** [comment]
what version of cucumberjvm are you using? I guess 4+ ? 

This may be related to parallel run. Try to upgrade allure-cucumber3jvm version to 2.8.1, try to disable parallel configuration and see if this helps.

**Comment by jsa34** [comment]
I'm using:
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-cucumber3-jvm</artifactId>
            <version>2.8.1</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>3.0.2</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>3.0.2</version>
        </dependency>


And for reporting in the POM I've got:

    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.9</version>
                <configuration>
                    <reportVersion>2.8.1</reportVersion>
                    <allureDownloadUrl>
                        https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/%s/allure-commandline-%s.zip
                    </allureDownloadUrl>
                </configuration>
            </plugin>
        </plugins>
    </reporting>

**Comment by jsa34** [comment]
Hello,

Apologies for the delay - just returned from Christmas hols.

I have now uploaded a sample project that was requested:
`https://github.com/jsa34/selenium-java-allure-framework`

Let me know if you need any more info.

Many thanks

PS - I added some extra stuff to the "AllureScreenshotPublisher" class to make it clearer in the logs for debugging.

**Comment by scormaq** [comment]
Hi there,
I would like to add that I'm facing this same issue with allure-cucumber3jvm (2.8.1). After some investigation I think the issue might be because of incorrect work of method [AllureLifecycle#stopStep(final String uuid)](https://github.com/allure-framework/allure-java/blob/30b8574322dbb0f45133155ec4a9a2a047d9813a/allure-java-commons/src/main/java/io/qameta/allure/AllureLifecycle.java#L511) (it is called in [last line](https://github.com/allure-framework/allure-java/blob/30b8574322dbb0f45133155ec4a9a2a047d9813a/allure-cucumber3-jvm/src/main/java/io/qameta/allure/cucumber3jvm/AllureCucumber3Jvm.java#L322) of `AllureCucumber3Jvm#handlePickleStep` method; if code for attaching screenshots is calling before its invocation, all works as expected). 

@jsa34 considering my conclusions above, you can try next workaround instead of using `beforeStepStop`:
```java
    @Override
    public void afterStepUpdate(StepResult result) {
        if (result.getStatus() != PASSED && result.getStatus() != SKIPPED) {
            byte[] screenShot = ((TakesScreenshot) DriverManager.getDriver()).getScreenshotAs(OutputType.BYTES);
            Allure.getLifecycle().addAttachment(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MMM-yy_hh:mm:ss")), "image/png", "png", screenShot);
        }
    }
```

**Comment by jsa34** [comment]
Hello!

Thanks for your feedback, @scormaq !

I tried your suggestion, and it appears you are correct - afterStepUpdate successfully attaches screenshots.

The name of the method "beforeStepStop"sounds like it should allow adding the screenshots because calling the method shouldn't stop the step, so perhaps this is a bug?

I am going to override the afterStepUpdate method for the moment until I hear otherwise.

Many thanks!

**Comment by jsa34** [comment]
Aha - so, now I am using:

`    
@Override
    public void afterStepUpdate(StepResult result) {
            byte[] screenShot = ((TakesScreenshot) DriverManager.getDriver()).getScreenshotAs(OutputType.BYTES);
            Allure.getLifecycle().addAttachment(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MMM-yy_hh:mm:ss")), "image/png", "png", screenShot);
    }
`

It appears to be fine on a single test, but when I ran the suite in parallel (25 threads) soon after starting, all 25 threads start logging:

`
04 Jan 2019 14:53:51,330 ERROR [TestNG-test=Surefire test-15] AllureLifecycle:563 - Could not add attachment: no test is running
`
Once these tests on the threads clear and the next test starts, it appears to no longer be a problem, but those 25 tests that were on the threads at the time that it outed that to the logs had no screenshots attached.  Not sure why this is happening?  Not enough memory for JVM?  Seems odd it affects ALL threads for the duration of the test until a new one is picked up and shortly after the threads are spun up.

**Comment by jsa34** [comment]
I have updated the project I mentioned before with the example:

[Sample project](https://github.com/jsa34/selenium-java-allure-framework)

It now has 2 test cases.

This doesn't, however, appear to throw the "No test" errors that my project I am working on does in the log, but it doesn't attach screenshots to one of the tests once the report is produced.

To run it, use the maven goals:

`
clean
install
site
-Dbrowser.name=ChromeRemote
-Dselenium.grid.url=http://GRIDLOCATION:4444/wd/hub
-DthreadCount=2
`

**Comment by scormaq** [comment]
@jsa34 you're using some 3rd party mechanism to run Cucumber-JVM tests in parallel, I think that might be the root of your problem. Cucumber-JVM prior version 4.x cannot run tests natively in parallel, so does not its allure adapter `AllureCucumber3Jvm`.

You have to either figure out how to properly integrate Allure into that mechanism, or wait for release of `AllureCucumber4Jvm` and rework your parallelization approach with native Cucumber-JVM mechanism.

 In any way, in my opinion it is not an issue with Allure adapter itself. The only mysterious part here for me is why `beforeStepStop()` method does not work as expected in conjunction with `AllureCucumber3Jvm`. :thinking:

**Comment by jsa34** [comment]
Thanks for the feedback, @scormaq 

I don't think the Cucable plugin is the issue - it just generates test runner files that are standard TestNG class runners in the /target dir and then the other part is to point to the test resources dir to pick these _IT.java runner classes from the /target dir rather than the project dirs.

In essence, the TestNG is using standard runner classes located in the /target dir - It worked seamlessly when on allure v1 - only became a prob with v2 upgrading.

I will try and make a more minimal test case to eliminate this possibility as I may have overlooked something  related to this...

**Comment by jsa34** [comment]
I have update the project to remove the Cucable plugin and the build helper as described above and still getting the same issues...

**Comment by jsa34** [comment]
Still trying to debug this and not sure where it is having problems...
Even with explicit runner classes for each test, when TestNG picks up the _IT.classes I am getting these missing screenshots... Both in my main project with ~300 tests (roughly 20% failure rate) and the project example:  [https://github.com/jsa34/selenium-java-allure-framework](https://github.com/jsa34/selenium-java-allure-framework)

Any suggestions?

**Comment by jsa34** [comment]
I couldn't get Cucumber 3 & cucumberjvm3 allure plugin to work happily, so I tried the suggested move to Cucumber 4 with native parallelisation, and all is good - I will update the project mentioned to reflect this, but I am still none the wiser as to why C-JVM3 didn't work - especially when calling the "beforeStepStop()" method.  I am using "afterStepUpdate()" method at the mo

**Comment by dreamflame51** [comment]
Not sure about C-JVM3, I switched from JVM1 to 4 and now using Cucumber, Maven, TestNG, Selenide etc... had issues with screenshots as well, tried what you suggested here, but without any luck, the thing that helped was
        SelenideLogger.addListener("AllureSelenide", new AllureSelenide().screenshots(true).savePageSource(true));

in the runners's default constructor

**Comment by aleksandar-stefanovic-tamedia** [comment]
> Still trying to debug this and not sure where it is having problems...
> Even with explicit runner classes for each test, when TestNG picks up the _IT.classes I am getting these missing screenshots... Both in my main project with ~300 tests (roughly 20% failure rate) and the project example: https://github.com/jsa34/selenium-java-allure-framework
> 
> Any suggestions?

Is there any chance that you can share demo project? I'm trying to add screenshots with allure on cucumber jvm4 with testng.

**Comment by jsa34** [comment]
Hey - I have released the framework as an open source project that we use internally.
We fixed this issue by changing the stage at which the screenshots were pushed to be at the "afterStepUpdate" method.

The project is here:  (documentation need improving!)
https://gitlab.developers.cam.ac.uk/jsa34/selenium-java-framework

Hope this helps!

**Comment by dudziakm** [comment]
I took the solution mentioned above:

> ```java
> @Override
>     public void afterStepUpdate(StepResult result) {
>             byte[] screenShot = ((TakesScreenshot) DriverManager.getDriver()).getScreenshotAs(OutputType.BYTES);
>             Allure.getLifecycle().addAttachment(LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MMM-yy_hh:mm:ss")), "image/png", "png", screenShot);
>     }
> ```

This works perfectly for me, even with many tests and many threads.

**Comment by omerfarukerkul** [comment]
> Hey - I have released the framework as an open source project that we use internally. We fixed this issue by changing the stage at which the screenshots were pushed to be at the "afterStepUpdate" method.
> 
> The project is here: (documentation need improving!) https://gitlab.developers.cam.ac.uk/jsa34/selenium-java-framework
> 
> Hope this helps!

Thank you, you really saved my life with the META-INF/services approach.
