### ISSUE TITLE
Executing Data Driven Testing append logs for all runs

### ISSUE THREAD

**Issue by sbhatta2018** [allure-framework/allure-java#293]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
I have three rows of data for data driven testing. All three rows gets executed and we can see the three test method in the report.
However, it appends logs for all the runs

#### What is the expected behavior?
Test run 1 should contain logs for test run 1
Test run 2 should contain logs for test run 2

#### Please tell us about your environment:

- Allure version:        2.1.0
- Test framework:        testng@6.8
- Allure adaptor:        allure-testng@2.0-BETA8
- Generate report using: allure-maven@2.18

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
@sbhatta2018 could you please add additional details on the problem? Having a code sample would be much appreciated

**Comment by baev** [comment]
closed due to no response
