### ISSUE TITLE
Not all @AfterMethod TestNG calls are always included in Allure report

### ISSUE THREAD

**Issue by tlytvyn** [allure-framework/allure-java#304]
<img width="638" alt="screen shot 2018-02-21 at 7 25 00 pm" src="https://user-images.githubusercontent.com/2183790/36497000-b24059de-1742-11e8-8abd-e437ab78b73d.png">
<img width="639" alt="screen shot 2018-02-21 at 7 25 20 pm" src="https://user-images.githubusercontent.com/2183790/36497001-b25f1464-1742-11e8-9542-76d87fe81f2d.png">

Precondition:
I have two methods in same class, executing that test class from xml <test> block by testng.
Newest Allure, testng 6.13.1 is used. 

Problem
1. @AfterMethod is adding a attachment in the code, (it has alwaysRun = true)
2. @Before method is failing for both methods in the class from Precondition

Result:
I can see @AfterMethod steps and attachments only for first invocated method in Allure Report

**Comment by baev** [comment]
@tlytvyn added a test for this case, everything works as expected. Probably your problem was related to other issues fixed via #324

**Comment by Hipatija2904** [comment]
This is again reproducible in allure-java-commons-2.13.8
