### ISSUE TITLE
Using @Step with Kotlin produces unexpected report 

### ISSUE THREAD

**Issue by abendt** [allure-framework/allure-java#309]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

using step annotation in Kotlin tests can result in an unexpected nested display of the step result (see Screenshot)

<img width="732" alt="bildschirmfoto 2019-01-18 um 22 11 24" src="https://user-images.githubusercontent.com/370821/51413124-1e498d00-1b6e-11e9-9137-f1d8bb8286bb.png">

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

https://github.com/abendt/allure-kotlin-sample

* run `./gradlew clean test allureReport allureServe` 
* navigate to the detailed test report and check how the step result is displayed

#### What is the expected behavior?

* there should be no nesting of the step result
* the single step result should be named properly according to the annotation value

#### What is the motivation / use case for changing the behavior?

enhance the user experience with kotlin

#### Please tell us about your environment:

check the sample project

#### Other information 

I think this is caused by the way kotlin generates the byte code. as my step annotated method uses the kotlin default-argument feature (https://kotlinlang.org/docs/reference/functions.html#default-arguments) the compiler seems to generate extra synthetic methods. These methods are most likely picked up by the Allure runtime.

**Comment by baev** [comment]
closed as stale
