### ISSUE TITLE
Link-related annotations don't resolve placeholders

### ISSUE THREAD

**Issue by mr-nothing** [allure-framework/allure-java#343]
**Describe the bug**
Placeholders used in link related annotations (Issue, TmsLink, Link) is not resolved into values.

For instance:

```
@TmsLink(value = "{scenario.taskNumber}")
public void test(Scenario scenario) {
// test goes here
}
```

The result of this operation will be https://tms-system.com/path/{scenario.taskNumber}
which is not correct.

**To Reproduce**
1. Use placeholder in TmsLink annotation
2. Placeholder is used as-is in the allure report.

**Expected behavior**
Placeholders are resolved into values they point to.

**Screenshots**

**Environment (please complete the following information):**

| Allure version | 2.6.0 |
| --- | --- |
| Test framework | testng@6.14.3 |
| Allure adaptor | allure-testng@2.6.0 |
| Generate report using | allure-maven@2.9 |

**Additional context**
No additional context.

**Comment by baev** [comment]
I'll consider adding such feature, but I don't think placeholders in links would be supported any time soon. 

At the moment you can add such link using Allure API:

```java
public void test(Scenario scenario) {
   Allure.tms(
        scenario.getTaskNumber(), 
        String.format("https://example.com/tms/%s", scenario.getTaskNumber())
   );
}
```
Or if you want to use placeholder from `allure.properties` you can create the method like this:

```java
public static void addLink(String key) {
   Link link = ResultsUtils.createTmsLink(key);
   Allure.tms(key, link.getUrl());
}
```

**Comment by mr-nothing** [comment]
This is actually exactly what I was looking for. Thank you for your help.
