### ISSUE TITLE
All configuration methods run by @Factory are listed under each "Set up"

### ISSUE THREAD

**Issue by yayaryna** [allure-framework/allure-java#350]
#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When running tests with TestNG @factory annotation, all configuration methods are listed under each "Set up" in allure report.
![2019-05-07_13h03_25](https://user-images.githubusercontent.com/7060626/57292371-3e27a100-70ca-11e9-8827-44dbdf52f269.png)

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Run the following class:
```java
public class TestPoc {

    @TestInstanceParameter("Iteration")
    int i = 1;

    public TestPoc() {

    }

    public TestPoc(int i) {
        this.i = i;
    }

    @BeforeClass
    public void beforeClass() {
    }

    @Test
    public void stepFailDemo() {
        try {
            failStep();
        } catch (AssertionError e) {/*do nothing*/
        }
    }

    @Step("Failing step")
    private void failStep() {
        Assert.fail("Failing an inner step  " + i);
    }


    @Factory
    public Object[] myFactory() {
        return new Object[]{new TestPoc(5), new TestPoc(6), new TestPoc(7)};
    }
}
```

#### What is the expected behavior?
Expected behavior - In each "set up" should be shown just related test configuration methods, not all of them.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.14.3 |
| Allure integration | allure-testng@2.13 |
| Generate report using | allure-maven@2.18 |

**Comment by Taredel** [comment]
Got same issue when @DataProvider + @Factory is used.
@baev any updates or workaround on this one?

**Comment by baev** [comment]
> workaround on this one?

don't know

> any updates

I'll try to assign someone to this one, stay tuned

**Comment by baev** [comment]
Closed as stale. Please create a GitHub discussion if the feature is still needed.
