### ISSUE TITLE
TestNG optional reporting for @After @Before failures

### ISSUE THREAD

**Issue by Gzyablik** [allure-framework/allure-java#356]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] feature request

#### What is the current behavior?
On Before/After(Class/Test) failures allure create reports as it was 'Test' and we have some inconvenience to displaying TeamCity allure reports. For example, next test class will report about two tests(one failed and one skipped)
`
public class Mytest {
    @BeforeMethod
    public void before() {
        Assert.fail();
    }
    @Test
    public void test() {
    }
}
`
This behavior was implemented with #135 

#### What is the expected behavior?
Reporting of After/Before method to be optional. For example, using configuration flags. 

#### What is the motivation / use case for changing the behavior?
Disabling the After/Before reporting was requested a sew times ago and those requests was rejected because of #135. My call is to make it optional to satisfy both behaviors with actual by default. 

#### Please tell us about your environment:
| Test framework | testng@6.14.3 |
| Allure integration | allure-testng@2.9.0 |
| Generate report using | teamcity allure plugin |

#### Other information 
We are using local snapshot with this workaround.
https://github.com/Gzyablik/allure-java/pull/1/files

**Comment by Proryanator** [comment]
I'd also love for this to get worked on/merged in. We recently upgraded to 2.13.6 of allure-testng, and didn't expect to see our config methods increasing the total count of tests.

If this were an added feature where you could decide to either include them or to not, that'd be nice. It throws our reporting numbers off now if anything breaks in config methods for TestNG.
