### ISSUE TITLE
[TestNG] Allure2 doesn't glue failed setUp method with successfully rerun

### ISSUE THREAD

**Issue by berrezzka** [allure-framework/allure-java#368]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure doesn't glue several test runs if the first failed in the setUp method.

Steps to reproduce :

Step 1: Run a test with some problem in setUp method (BeforeClass): there are 2 test results in the generated allure report. 
Step 2:  Fix the problem in the setUp method, run test again: test pass successfully, but regenerated allure report is showing again privously failed setUp method as a separate failed test.

![first](https://user-images.githubusercontent.com/28677916/59099842-fe541380-892c-11e9-8086-515608874ecc.png)
![second_1](https://user-images.githubusercontent.com/28677916/59099843-fe541380-892c-11e9-833a-45fb073cc3a3.png)
![second_2](https://user-images.githubusercontent.com/28677916/59099841-fe541380-892c-11e9-9114-d4f07e06ae85.png)

#### What is the expected behavior?
As Allure can glue several test runs  I expect not to see failed test in the last successful run, only in 'Retries' tab.

| Allure version | 2.11.0 |
| Test framework | testng@6.14.3 |
| Allure integration | allure-testng@ 2.12.1 |
| Generate report using | allure-maven@2.10.0 |

**Comment by baev** [comment]
the reason of such behaviour is that Allure TestNG integration report fake test result for failed fixtures in order to notify users. Every test result stored in separate file (filename contains UUID in order to prevent conflicts in concurrent environment). So when you rerun your tests and every fixture passed there no more fake result to override previous failure. 

I can't see a way we can get rid of such behaviour, so I suggest you to clean up allure-results folder between runs.
