### ISSUE TITLE
AddAtachment api need to take a few files

### ISSUE THREAD

**Issue by choojoykin** [allure-framework/allure-java#374]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [X ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure.addAttachment() takes 1 file for attach.

#### What is the expected behavior?
Allure.addAttachment() takes collection of files

#### What is the motivation / use case for changing the behavior?
 There are cases when you need to add several files to a step at once, eg all messages from mq broker.

#### Please tell us about your environment:

| Allure version | 2.10.0 |
| --- | --- |
| Test framework | testng@6.14.3 |
| Allure integration | allure-testng@2.10 |
| Generate report using | allure-maven@2.10 |

**Comment by gavrilfb** [comment]
Why not call the add attachment methods multiple times?
