### ISSUE TITLE
Corrupted STDOUT by directly writing to native stream in forked JVM 1

### ISSUE THREAD

**Issue by Lewka** [allure-framework/allure-java#378]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report

#### What is the current behavior?
 При запуске тестов через команду мавена `mvn clean test` получаю ошибку типа `Corrupted STDOUT by directly writing to native stream in forked JVM 1.` если подключен логгер `log4j-slf4j` и подключенном модуле `allure-junit-platform`, если выключить логгер `log4j-slf4j` и подключить `slf4j-simple` то все будет логироваться нормально, без ошибок.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
[Ссыль на проект](https://github.com/Lewka/allure-junit5-stdout-error)
В помке раскоментировать нужный логер и выполнить команду `mvn clean test`

#### What is the expected behavior?

Сообщения логируются, ошибка отсутствует

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework |  junit@5.4.2|

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
not related to allure

**Comment by SporeTec** [comment]
This happened to our project too and only after adding allure and its dependencies, could you please share more insights where this is coming from?

**Comment by lucas-nguyen-17** [comment]
@florianmautendorfer I got the same issue, then I found this. https://stackoverflow.com/questions/55272870/surefire-maven-plugin-corrupted-stdout-by-directly-writing-to-native-stream-in.
It clears out the warning and show the log that has been hidden.

```<plugin>
      <artifactId>maven-surefire-plugin</artifactId>
      <version>3.0.0-M5</version>
      <configuration>
        <!-- Activate the use of TCP to transmit events to the plugin -->
        <forkNode implementation="org.apache.maven.plugin.surefire.extensions.SurefireForkNodeFactory"/>
      </configuration>
    </plugin>```
