### ISSUE TITLE
allure-selenide doesn't work correct with Selenide 5.x multi-browser function in some cases 

### ISSUE THREAD

**Issue by vinogradoff** [allure-framework/allure-java#379]
allure/allure-selenide 2.12.1

Beginning with Selenide 5.x WebDriverRunner.getWebDriver() can delivery the wrong webdriver depending on configuration, if multiple browser are used in a single test.

Also screenshot logger crashes trying to make a screenshot when open (=WebDriver.get(url)) function fails to open the browser session correctly.

Reproducible example for the second case:
https://github.com/vinogradoff/sandbox-selenide/blob/master/src/test/java/org/selenide/allure/SimpleTest.java

**Comment by vinogradoff** [comment]
Methods to be fixed: 

https://github.com/allure-framework/allure-java/blob/09b259f97ff0bb4064f3bbe7eb3b4b9fbe308fe5/allure-selenide/src/main/java/io/qameta/allure/selenide/AllureSelenide.java#L71

https://github.com/allure-framework/allure-java/blob/09b259f97ff0bb4064f3bbe7eb3b4b9fbe308fe5/allure-selenide/src/main/java/io/qameta/allure/selenide/AllureSelenide.java#L81

**Comment by asolntsev** [comment]
@baev What about a new release?
