### ISSUE TITLE
Allure does not fail a test when Selenide command throws exception

### ISSUE THREAD

**Issue by SeleniumTestAB** [allure-framework/allure-java#382]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
When exception occurs on one of Selenide commands ```selenideElement.waitUntill(condition, timeout) ``` in nested step, then step is marked as failed but the test overall is marked as passed

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Create a test with selenide using ```selenideElement.waitUntill()``` method with condition that should fail, also it should be nested in some step.

#### What is the expected behavior?
Test is marked as failed when such step fails

#### Please tell us about your environment:

| Allure version | 2.12.1 |
| Allure selenide|2.12.1 |
| Test framework | testng@6.14.3 |
| Allure integration | allure-testng@2.12.1 |
| Generate report using | allure-commandline@2.12.1 on Jenkins |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
Allure doesn't control test execution, it actually behaves as logger framework - you can report some events to Allure with different statuses, thats it. Test marked as failed when TestNG reports that tests as failed.
