### ISSUE TITLE
Inherit annotations for nested classes (junit5)

### ISSUE THREAD

**Issue by eroshenkoam** [allure-framework/allure-java#391]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### Please tell us about your environment:

| Allure version | 2.13.0 |
| --- | --- |
| Test framework | juni-plaform@5.4.0 |
| Allure integration | allure-junit-platform@2.13.0 |
| Generate report using | allure@2.13.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by Ielay** [comment]
Hello, is there some work in progress on this issue? This one might be very helpful in our test cases

**Comment by baev** [comment]
@Ielay, could you please provide additional details on your use cases?

**Comment by Ielay** [comment]
We are using JUnit5 as a testing framework along with allure to document our test cases.

The story is mostly about tests on Spring controller layer classes. One day we realised that they became too huge to maintain (too much tests within a single class, too much utility methods and most of them not general/not applicable to each test case). So we decided to split each class tests into nested classes, each class is for one **Feature**, like the following:

**Before:**
```java
@Suite(...)
@Epic(...)
class EntityXController {

    @Test
    @Feature(Feat1)
    void feat1_test1() {...}
    
    ...
    
    @Test
    @Feature(Feat1)
    void feat1_testN1() {...}
    
    ...
    
    @Test
    @Feature(FeatM)
    void featM_test1() {...}
    
    ...
    
    @Test
    @Feature(FeatM)
    void featM_testNM() {...}
}
``` 

**After:**
```java
@Suite(...)
@Epic(...)
class EntityXController {

    @Nested
    @Feature(Feat1)
    class Feature1 {
    
        @Test
        void feat1_test1() {...}
        
        ...
        
        @Test
        void feat1_testN1() {...}
    }
    
    ...
    
    @Nested
    @Feature(FeatN)
    class FeatureN {
    
        @Test
        void featM_test1() {...}
    
        ...
    
        @Test
        void featM_testNM() {...}
    }
}
```

But after that we realised that we must provide **Suite** and **Epic** info **on each nested class**. And that leads to code duplicity and there is a chance to forget to put all those annotations on some nested class. So it would be really nice to have a possibility to put annotations only on enclosing class.

**Comment by is-ivanov** [comment]
I would also like the Epic annotation to be inherited by nested classes

**Comment by baev** [comment]
If you are interested in the issue, don't forget to put the vote on (👍). Issues with the most votes have much more attention from the team.

**Comment by standbyoneself** [comment]
Really want to merge DisplayName annotation. Example:
```java
@DisplayName("Admin Page")
public class AdminPageTests {
    @Nested
    @DisplayName("Subjects")
    class Subjects {
        ...
    }
}
```

This code should generate nested suites in report or generate its name like this: "Admin Page" > "Subjects", not "Subjects"

**Comment by LukeSP** [comment]
I am trying to do something similar with the @DisplayName annotation in nested classes as well for Allure Suites. Is this something which will be added in the future?
