### ISSUE TITLE
Allure Junit5 throw NoSuchMethodError warning

### ISSUE THREAD

**Issue by choojoykin** [allure-framework/allure-java#393]
#### I'm submitting a ... 
  - [ x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
allure-junit5 versions above 2.10.0 throw warning
` org.junit.platform.launcher.core.TestExecutionListenerRegistry lambda$notifyEach$1
WARNING: TestExecutionListener [io.qameta.allure.junitplatform.AllureJunitPlatform] threw exception for method: executionStarted(TestIdentifier [uniqueId = '[engine:junit-jupiter]/[class:Tests]/[method:Cancellation()]', parentId = '[engine:junit-jupiter]/[class:Tests]', displayName = 'improvements', legacyReportingName = 'Cancellation()', source = MethodSource [className = 'Tests', methodName = 'Cancellation', methodParameterTypes = ''], tags = [], type = TEST])
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: io.qameta.allure.util.AnnotationUtils.getLinks(Ljava/lang/reflect/AnnotatedElement;)Ljava/util/Set;
    at io.qameta.allure.junitplatform.AllureJunitPlatform.startTestCase(AllureJunitPlatform.java:220)
    at io.qameta.allure.junitplatform.AllureJunitPlatform.executionStarted(AllureJunitPlatform.java:121)
    at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionStarted$6(TestExecutionListenerRegistry.java:99)
    at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67)`

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Just run junit5 test with allure-junit5 ver above 2.10.0

#### Please tell us about your environment:

| Allure version | 2.13.0 |
| --- | --- |
| Test framework | junit5@5.5.1 |
| Allure integration | allure-junit5@2.13.0 |
| Generate report using | allure-maven@2.10.0 |

**Comment by choojoykin** [comment]
have older versions in dependency tree

**Comment by ColceriuVlad** [comment]
Hello, what was the sollution to this problem? I am also encountering it and cant figure it out
