### ISSUE TITLE
Test body is missing in (cucumber) testNG report

### ISSUE THREAD

**Issue by pokeahontas** [allure-framework/allure-java#398]
Hi, I'm submitting a bug report:
I use `TestNGCucumberRunner` to run cucumber test cases via TestNG and the report is successfully built but I do not see the test steps in the report, I only see setup and tear down.

![Bildschirmfoto 2019-10-28 um 13 22 37](https://user-images.githubusercontent.com/3076274/67678107-15e87300-f986-11e9-876e-4b0c58c8b92d.png)

Anyone know how to fix this or this a bug?

| Allure version | 2.9.0 |
| Test framework | cucumber-testng@4.7.2 |
| Allure integration | allure-testng@2.0-BETA20 |
| Generate report using gradle |

**Comment by mrbaco** [comment]
Hello, @pokeahontas 
I have cucumber+testng environment and I had the same problem.
I decide to use Allure plugin for cucumber **io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm** (Cucumber 5.6.0) and I added to CucumberOptions this:
`plugin = {"io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm"}`

and dependency to build.gradle:
`// https://mvnrepository.com/artifact/io.qameta.allure/allure-cucumber5-jvm
    implementation group: 'io.qameta.allure', name: 'allure-cucumber5-jvm', version: '2.13.2'`

Maybe it will help.

**Comment by livastar** [comment]
> io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm

the same issue but with this stack - gradle-testng-cucumber-allure....

**Comment by aleksandar-stefanovic-tamedia** [comment]
Are there any solutions for this?

**Comment by mrbaco** [comment]
Additional code to build.gradle:
`
allure {
    version = '2.8.1'

    autoconfigure = false
    aspectjweaver = true

    useCucumberJVM() {
        version = '2.13.2'
    }
}
`

**Comment by baev** [comment]
https://github.com/allure-framework/allure-java/issues/398#issuecomment-616418639
