### ISSUE TITLE
AllureTestNg could not be instantiated

### ISSUE THREAD

**Issue by redfirefox** [allure-framework/allure-java#409]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
There was an error in the forked processorg.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

doesn't work with  selenide 5.5.1, allure-testng 2.13.0, allure-selenide 2.13.0, testng 7.0.0
work only with selenide 5.2.2, allure-testng 2.9.0, allure-selenide 2.9.0, testng 7.0.0

if I upgrade version selenide to 5.2.3, allure-testng 2.9.0, allure-selenide 2.9.0, testng 7.0.0
then
io.qameta.allure.selenide.AllureSelenide.beforeEvent(Lcom/codeborne/selenide/logevents/LogEvent;)V

if I upgrade version allure-testng to 2.10.0, allure-selenide 2.10.0, selenide 5.2.2, testng 7.0.0
then
There was an error in the forked processorg.testng.ITestNGListener: Provider io.qameta.allure.testng.AllureTestNg could not be instantiated

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | testng@6.8 |
| Allure integration | allure-testng@2.0-BETA11 |
| Generate report using | allure-maven@2.18 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by kathyrollo** [comment]
This appears to be versioning incompatibilities:

https://stackoverflow.com/questions/47341559/allure-testng-maven-org-testng-itestnglistener-provider-io-qameta-allure-testn

https://stackoverflow.com/questions/53612867/io-qameta-allure-testng-alluretestng-could-not-be-instantiated

**Comment by asolntsev** [comment]
@redfirefox Did you already solve your issue?
If not, please provide
1. The full stack trace of `Provider io.qameta.allure.testng.AllureTestNg could not be instantiated`
2. Output of `mvn dependency:tree` in both setups (when issue happens and doesn't happens). 
  2.1 In case of Gradle, use `./gradlew dependencies`.
