### ISSUE TITLE
Attachments not working for Configuration Methods using IInvokedMethodListener (Allure-TestNG 

### ISSUE THREAD

**Issue by MohabMohie** [allure-framework/allure-java#419]
### I'm submitting a ... 
  **- [X] bug report**
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
**Issue description:**
- I'm implementing the `IInvokedMethodListener` for TestNG
- Inside it I have Overridden the `afterInvocation` method
- I use this to create a log for the current test method `Reporter.getOutput(testResult)`
- Then I try to attach this log file using this code
`Allure.addAttachment(attachmentDescription, "text/plain", attachmentContent, ".txt");`
- This works as expected for all `@Test` methods, but it doesn't work for configuration methods like `@BeforeMethod` and `@AfterMethod`
- This error is shown in the console `[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running`

**Debugging Information**

Upon debugging this issue I traced it to this method
`String io.qameta.allure.AllureLifecycle.prepareAttachment(String name, String type, String fileExtension)`

Apparently `threadContext.getCurrent();` is returning empty instead of returning the UUID of the current configuration method.

**This behavior is shown if I'm running any test, but if I'm debugging it becomes intermittent, and sometimes works as expected!!!**

#### What is the expected behavior?
The attachment should be added successfully, and this error should not happen.

#### What is the motivation / use case for changing the behavior?
This impacts reporting attachments for any configuration method.

#### Please tell us about your environment:
| Test framework | testng@7.0.0 |
| Allure integration | allure-testng@2.13.1 |
| AspectJ Weaver | aspectjweaver | 1.9.5 |
| Java run-time environment | JDK | 13 |
| IDE | Eclipse | Build id: 20191212-1212 |

#### Other information 

- I couldn't downgrade to acpectj 1.8.0 because it's not working with JDK 13
- Tried using a different listener 'IConfigurationListener' but the same issue persisted

**Comment by MohabMohie** [comment]
The same issue happens when running outside eclipse using apache-maven-3.6.3 / Windows 10 / PowerShell

**Comment by Psavel** [comment]
I was wondering if someone found how to sort out this problem?

**Comment by EugeneShchur** [comment]
Also having exactly the same issue for fails in @BeforeMethod and the same "Could not add attachment: no test is running" error

**Comment by zxj782819517** [comment]
 public void onTestFailure(ITestResult tr) {Allure.addAttachment(....)} 

[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running

**Comment by PePeLM** [comment]
I have exactly the same issue, running form jenkins. Any ideas how to fix it? Was trying to downgrade allure-testng version and aspectj but it's not working. For me it's working randomly once it's adding attachments, once it's not....

**Comment by baev** [comment]
> For me it's working randomly once it's adding attachments, once it's not....

yeah, that's because Allure is using the same API to process TestNG lifecycle events, and there is no guarantee in what order this hooks are executed. So basically if your hook goes first, you'll see the attachment in the report, otherwise you'll not.

**Comment by PePeLM** [comment]
> > For me it's working randomly once it's adding attachments, once it's not....
> 
> yeah, that's because Allure is using the same API to process TestNG lifecycle events, and there is no guarantee in what order this hooks are executed. So basically if your hook goes first, you'll see the attachment in the report, otherwise you'll not.

Is there any workaround or fix possible ?

**Comment by baev** [comment]
I can suggest using Allure Lifecycle listeners like io.qameta.allure.listener.StepLifecycleListener or io.qameta.allure.listener.TestLifecycleListener

**Comment by baev** [comment]
keep allure-testng and use Allure Lifecycle listeners instead of native testng hooks if needed

**Comment by PePeLM** [comment]
Hi, I created a class like that and added the META-INF services listener in my resource folder is it enough?
Or should I now add it to testng.xml config file in the listeners section?
```
public class AllureListener implements TestLifecycleListener {
	BaseTest currentClass;
	protected static Logger logger = LogManager.getLogger(AllureListener.class);
	  
	@Override
	    public void afterTestStop(final TestResult result) {
			logger.info("after Test");
			if(result.getStatus().equals(Status.FAILED)) {
				List<IWebDriver> driverInstances = currentClass.getDriverFactory().getOpenDriverInstances();
			
				for (IWebDriver driverInstance : driverInstances) {
					((TakesScreenshot) driverInstance).getScreenshotAs(OutputType.BYTES);
					}
		
	    }
```


Thanks for helping me out !

**Comment by PePeLM** [comment]
@baev Iadded TestLifcycleListner and I'm still getting 13:16:01.404 [main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running.

**Comment by vasivarga** [comment]
> @baev I've manage to do it ! Thanks for help.

How?

**Comment by PePeLM** [comment]
> > @baev I've manage to do it ! Thanks for help.
> 
> How?

1. I've created file  **io.qameta.allure.listener.StepLifecycleListener** in the resource folder in location **src/main/resources/META-INF/services/**
2. In the file you need to specify the full package to your new Allure Step Listener class. (in my case **testautomation.tests.util.AllureStepListener**)
3.  Create class **AllureStepListener** that implements **StepLifecycleListener** and add screenshot creation in it(my class below).

That's all - it works for me.

```
public class AllureStepListener implements StepLifecycleListener {
	
	protected static Logger logger = LogManager.getLogger(AllureStepListener.class);
	
	@Override
    public void beforeStepStop(final StepResult result) {
			
		if(result.getStatus().equals(Status.FAILED) || result.getStatus().equals(Status.BROKEN)) {
			screenshot();
			result.setStatus(Status.FAILED);
	    }
		
	}

		 @Attachment(value = "Screenshot", type = "image/png")
		 public byte[] screenshot() {
				List<IWebDriver> driverInstances = WebDriverFactory.getInstance().getOpenDriverInstances();
				byte[] screenshotByte = null;
				for (IWebDriver driverInstance : driverInstances) {
					 screenshotByte = ((TakesScreenshot) driverInstance).getScreenshotAs(OutputType.BYTES);
					}
			
				return screenshotByte;
		   
		 }
	}
```

**Comment by vasivarga** [comment]
> > > @baev I've manage to do it ! Thanks for help.
> > 
> > 
> > How?
> 
> 1. I've created file  **io.qameta.allure.listener.StepLifecycleListener** in the resource folder in location **src/main/resources/META-INF/services/**
> 2. In the file you need to specify the full package to your new Allure Step Listener class. (in my case **testautomation.tests.util.AllureStepListener**)
> 3. Create class **AllureStepListener** that implements **StepLifecycleListener** and add screenshot creation in it(my class below).
> 
> That's all - it works for me.
> 
> ```
> public class AllureStepListener implements StepLifecycleListener {
> 	
> 	protected static Logger logger = LogManager.getLogger(AllureStepListener.class);
> 	
> 	@Override
>     public void beforeStepStop(final StepResult result) {
> 			
> 		if(result.getStatus().equals(Status.FAILED) || result.getStatus().equals(Status.BROKEN)) {
> 			screenshot();
> 			result.setStatus(Status.FAILED);
> 	    }
> 		
> 	}
> 
> 		 @Attachment(value = "Screenshot", type = "image/png")
> 		 public byte[] screenshot() {
> 				List<IWebDriver> driverInstances = WebDriverFactory.getInstance().getOpenDriverInstances();
> 				byte[] screenshotByte = null;
> 				for (IWebDriver driverInstance : driverInstances) {
> 					 screenshotByte = ((TakesScreenshot) driverInstance).getScreenshotAs(OutputType.BYTES);
> 					}
> 			
> 				return screenshotByte;
> 		   
> 		 }
> 	}
> ```

Thanks! I'll try it. Did you include AllureStepListener in the test suite XML or anywhere?

**Comment by PePeLM** [comment]
> > > > @baev I've manage to do it ! Thanks for help.
> > > 
> > > 
> > > How?
> > 
> > 
> > 
> > 1. I've created file  **io.qameta.allure.listener.StepLifecycleListener** in the resource folder in location **src/main/resources/META-INF/services/**
> > 2. In the file you need to specify the full package to your new Allure Step Listener class. (in my case **testautomation.tests.util.AllureStepListener**)
> > 3. Create class **AllureStepListener** that implements **StepLifecycleListener** and add screenshot creation in it(my class below).
> > 
> > That's all - it works for me.
> > ```
> > public class AllureStepListener implements StepLifecycleListener {
> > 	
> > 	protected static Logger logger = LogManager.getLogger(AllureStepListener.class);
> > 	
> > 	@Override
> >     public void beforeStepStop(final StepResult result) {
> > 			
> > 		if(result.getStatus().equals(Status.FAILED) || result.getStatus().equals(Status.BROKEN)) {
> > 			screenshot();
> > 			result.setStatus(Status.FAILED);
> > 	    }
> > 		
> > 	}
> > 
> > 		 @Attachment(value = "Screenshot", type = "image/png")
> > 		 public byte[] screenshot() {
> > 				List<IWebDriver> driverInstances = WebDriverFactory.getInstance().getOpenDriverInstances();
> > 				byte[] screenshotByte = null;
> > 				for (IWebDriver driverInstance : driverInstances) {
> > 					 screenshotByte = ((TakesScreenshot) driverInstance).getScreenshotAs(OutputType.BYTES);
> > 					}
> > 			
> > 				return screenshotByte;
> > 		   
> > 		 }
> > 	}
> > ```
> 
> Thanks! I'll try it. Did you include AllureStepListener in the test suite XML or anywhere?

Nope.

**Comment by DodonchikA** [comment]
> > > @baev I've manage to do it ! Thanks for help.
> > 
> > 
> > How?
> 
> 1. I've created file  **io.qameta.allure.listener.StepLifecycleListener** in the resource folder in location **src/main/resources/META-INF/services/**
> 2. In the file you need to specify the full package to your new Allure Step Listener class. (in my case **testautomation.tests.util.AllureStepListener**)
> 3. Create class **AllureStepListener** that implements **StepLifecycleListener** and add screenshot creation in it(my class below).
> 
> That's all - it works for me.
> 
> ```
> public class AllureStepListener implements StepLifecycleListener {
> 	
> 	protected static Logger logger = LogManager.getLogger(AllureStepListener.class);
> 	
> 	@Override
>     public void beforeStepStop(final StepResult result) {
> 			
> 		if(result.getStatus().equals(Status.FAILED) || result.getStatus().equals(Status.BROKEN)) {
> 			screenshot();
> 			result.setStatus(Status.FAILED);
> 	    }
> 		
> 	}
> 
> 		 @Attachment(value = "Screenshot", type = "image/png")
> 		 public byte[] screenshot() {
> 				List<IWebDriver> driverInstances = WebDriverFactory.getInstance().getOpenDriverInstances();
> 				byte[] screenshotByte = null;
> 				for (IWebDriver driverInstance : driverInstances) {
> 					 screenshotByte = ((TakesScreenshot) driverInstance).getScreenshotAs(OutputType.BYTES);
> 					}
> 			
> 				return screenshotByte;
> 		   
> 		 }
> 	}
> ```

Thank you so much!!!

**Comment by MohabMohie** [comment]
the proposed workaround is not working for me
![image](https://user-images.githubusercontent.com/19201898/231079193-d0eb4b74-3bee-4271-90c2-ed735cc1a33e.png)
![image](https://user-images.githubusercontent.com/19201898/231079475-45d3506c-ddff-46ca-9315-7991679f1952.png)


Execution doesn't even reach the breakpoint.

**Comment by MohabMohie** [comment]
@PePeLM I tried both and neither of them worked for me.

**Comment by kamilrychta** [comment]
@MohabMohie Hey, Did you manage to solve this problem on your project?
I'm having same issue - calling 'Allure.addAttachment' method on onTestFailure(ITestResult result) return an error:
'[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running'

**Comment by gaurav-unifydots** [comment]
I'm having same issue - calling 'Allure.addAttachment' method on onTestFailure(ITestResult result) return an error:
'[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running'

**Comment by gaurav-unifydots** [comment]
> @MohabMohie Hey, Did you manage to solve this problem on your project? I'm having same issue - calling 'Allure.addAttachment' method on onTestFailure(ITestResult result) return an error: '[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running'

Are you able to solve this problem

**Comment by kamilrychta** [comment]
I've fixed that by adding 'IInvokedMethodListener' interface inside my report class. There is a method called 'afterInvocation' inside this interface and I moved my Allure code to this method.
