### ISSUE TITLE
Add the opportunity to disable(enable on-demand)  AllureJunit5 TestExecutionListener.

### ISSUE THREAD

**Issue by yampi4ek** [allure-framework/allure-java#428]
Junit5 launcher loads listers via SPI mechanism, because the listener defined in `resources/META-INF/services`, so it is loaded every time. I have a case where the default listener behavior does not meet my requirements so I have to write my own one. But I faced with issue that 2 listeners are invoked and 2 reports are generated. So I do not want the Allure Junit 5 TestExecutionListener been executed at all. 
I had to rewrite default behavior for the next reasons: 
I'm trying to change report generation for Allure to override the test status of failed tests. Tests that failed by assertion are marked as FAILED and red in a final report. Tests that failed due to timeout - BROKEN and yellow. I need to make all the reasons for test failures FAILED and red.

We found the next solution to fix it. Just exclude allure sub dependency via build tool. 
```
testCompile ('io.qameta.allure:allure-junit5:'2.12.1') { 
    exclude group: 'io.qameta.allure', module: 'allure-junit-platform`) 
}
```
But I would like to have a more elegant solution for this.

**Comment by baev** [comment]
you can use our dependencies with `spi-off` classifier. They are the same but has no `META-INF/services` resources included, so will not be loaded automatically

**Comment by yampi4ek** [comment]
Hello @baev,
 I just wondering, could it be founded in documentation? I think I looked through the documentation and could not find any mentions about this classifier. I would appreciate it if you could share the link.
Thanks.

**Comment by sksamuel** [comment]
@baev Is it possible to exclude the junit platform dependency?
Switching junit5 to spi-off removes that, but allure-junit-platform seems to be brought in by the plugin ?

**Comment by baev** [comment]
for Gradle users there is `dependencySubstitution` option available

```
configurations {
    all {
        resolutionStrategy {
            dependencySubstitution {
                substitute(module("io.qameta.allure:allure-junit5:2.18.1")).apply {
                    with(module("io.qameta.allure:allure-junit5:2.18.1:spi-off"))
                        because("SPI disabled")
                    }
                }
                substitute(module("io.qameta.allure:allure-junit-platform:2.18.1")).apply {
                    with(module("io.qameta.allure:allure-platform:2.18.1:spi-off"))
                        because("SPI disabled")
                    }
                }
            }
        }
    }
}
```

**Comment by sksamuel** [comment]
Ok that might be a workaround. Are there plans to fix this "properly" in a future release?

**Comment by baev** [comment]
@sksamuel could you please create a separate issue (this one is closed few years ago) and describe what are exact problem you're trying to solve. Thanks
