### ISSUE TITLE
Optional @Return for @Step methods with return value

### ISSUE THREAD

**Issue by kathyrollo** [allure-framework/allure-java#437]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
There is no way to display the returned value of a method.

#### What is the expected behavior?
`@Return` is an optional annotation that can be used with `@Step` only (unless there are other use cases).

Proposed Solution:
```
@Step("Compute total interest")
@Return(name = "total interest")
public BigDecimal computeInterest() {
	return BigDecimal.valueOf(getSimpleInterest()).setScale(0, RoundingMode.HALF_UP);
}
```

Proposed Output:

![allure_step_return](https://user-images.githubusercontent.com/28589393/79122571-596f5600-7ddb-11ea-8859-25a4879bfa09.PNG)

When returning custom objects, `toString()` needs to be overridden.

#### What is the motivation / use case for changing the behavior?
- Provides conclusive results of what occurred during test execution particularly for methods that return computed values to be asserted with actual values on a webpage (a very common scenario).
- Complements the parameter display of `@Step`.

#### Please tell us about your environment:

| Allure version | 2.13.2 |
| --- | --- |
| Test framework | junit@5.6.2 |
| Allure integration | allure-junit5@2.13.2 |
| Generate report using | allure-maven@2.10.0 |

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
It can be done by custom aspect or by using Allure Runtime API:

```java
Allure.step((context) -> {
    var result = doSomething();
    return context.parameter("total interest", result);
});
```

I don't think introducing a new annotation is a good idea since it is quite specific. However, it could be easily implemented as a custom extension module to Allure, and if that becomes popular, I would be happy to make it official.
