### ISSUE TITLE
How to integrate allure report with io.cucumber latest version. Please provide some examples

### ISSUE THREAD

**Issue by suryapaandeeswaran** [allure-framework/allure-java#441]
How to integrate allure report with io.cucumber latest version. Please provide some examples

**Comment by aleksandar-stefanovic-tamedia** [comment]
I've tried same like with Cucumber4 but have no success. 
`@CucumberOptions(
        features = "src/test/resources/features",
        glue = "ch.tamedia.steps",
        plugin = {
                "json:target/cucumber/RunnerResults.json",
                "io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm"
        }
)
public class Runner {

    private TestNGCucumberRunner testNGCucumberRunner;

    @BeforeClass(alwaysRun = true)
    public void setUpClass() {
        testNGCucumberRunner = new TestNGCucumberRunner(this.getClass());
    }

    @Test(dataProvider = "features")
    public void feature(PickleWrapper eventWrapper, FeatureWrapper cucumberFeature) {
        testNGCucumberRunner.runScenario(eventWrapper.getPickle());
    }

    @DataProvider(parallel = true)
    public Object[][] features() {
        return testNGCucumberRunner.provideScenarios();
    }

    @AfterClass(alwaysRun = true)
    public void tearDownClass() {
        testNGCucumberRunner.finish();
    }
}`

**Comment by aleksandar-stefanovic-tamedia** [comment]
Are there any solutions for this?

**Comment by baev** [comment]
You can find updated and working examples in our [allure-examples](https://github.com/allure-examples?q=cucumber7&type=all&language=java&sort=) organisation.

Reference documentation available as well https://allurereport.org/docs/cucumberjvm/
