### ISSUE TITLE
[Junit 5] Steps are missing in report in case if test failed in @BeforeAll()

### ISSUE THREAD

**Issue by Legionivo** [allure-framework/allure-java#443]
#### I'm submitting a ... 
  - [X] bug report

#### What is the current behavior?
Report is empty If test fails in method under `@BeforeAll()` annotation. allure-results folder contain data, but this data is not displayed in final html report.
See screenshots below as example.  

#### What is the expected behavior?
Methods annotated with `@BeforeAll()` annotation should be processed and displayed in report the same as methods annotated with `@BeforeEach()` annotation. 

#### Please tell us about your environment:

| Allure version | 2.13.2 |
| --- | --- |
| Test framework | junit5@5.6.2 |
| Allure integration | allure-junit5@2.13.2 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)
`@BeforeAll()`
![Screenshot from 2020-05-20 12-27-39](https://user-images.githubusercontent.com/12167296/82436128-a0fd9780-9a95-11ea-9550-26142820b886.png)

`@BeforeEach()`

![Screenshot from 2020-05-20 12-32-53](https://user-images.githubusercontent.com/12167296/82436393-0a7da600-9a96-11ea-8ba6-d2680d3fc9b3.png)

**Comment by mszajowskiwr** [comment]
@Legionivo did you find any workaround for this issue?

**Comment by Legionivo** [comment]
> @Legionivo did you find any workaround for this issue?

Hello, nope, I didn't, because I did not try to search workaround.

**Comment by zferenczik** [comment]
Looks like JUnit5 not fully supported :(
It's a must if you run functional regression tests.

**Comment by martinsefcik** [comment]
It looks like it is happening because of missing child (container -> result) reference in in test container json file.

I was able to get it working correctly by modifying `io.qameta.allure.junitplatform.AllureJunitPlatform#stopTestContainer` method. I commented the following `if` there:

```java
//        if (testIdentifier.isTest()) {
            getTest(testIdentifier).ifPresent(children::add);
//        }
```

I'm not sure yet if this change breaks something else or not, but existing junits in allure-junit-platform module are passing.

**Comment by S-Kerrigan** [comment]
> I'm not sure yet if this change will break something else or not, but existing junits in allure-junit-platform module are passing.

Yep, also helped me: now in report saw steps&attachments when "test broken"

**Comment by korpus95** [comment]
> It looks like it is happening because of missing child (container -> result) reference in test container json file.
> 
> I was able to get it working correctly by modifying `io.qameta.allure.junitplatform.AllureJunitPlatform#stopTestContainer` method. I commented the following `if` there:
> 
> ```java
> //        if (testIdentifier.isTest()) {
>             getTest(testIdentifier).ifPresent(children::add);
> //        }
> ```
> 
> I'm not sure yet if this change will break something else or not, but existing junits in allure-junit-platform module are passing.

@martinsefcik @S-Kerrigan 
Can you tell me how you solved the problem in more detail? I don't understand how to do it..

**Comment by martinsefcik** [comment]
@korpus95 I didn't solve the problem, I just proposed what needs to be changed in allure-java library to fix it.

**Comment by korpus95** [comment]
@Legionivo Have you found a way to solve the problem?

**Comment by korpus95** [comment]
@Legionivo  I checked, the problem is solved
