### ISSUE TITLE
[Selenide] Unused SelendeElement fields are shown in the report 

### ISSUE THREAD

**Issue by pavelnazimok** [allure-framework/allure-java#445]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?

`SelendeElement` fields declared with locators chaining are shown in the report even when not used in the test.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

I have AllureSelenide listener enabled:
```Java
SelenideLogger.addListener("AllureSelenide", new AllureSelenide().includeSelenideSteps(true));
```

I have PageObject class with elements declared using locators chaining:
```Java
public class PatientPage {

    private final SelenideElement container = $("#patientNavigation");

    private final SelenideElement
            newPatientButton = container.$("#btnNewPatient_CD"),
            activeTab = container.$("#navigationLeftTab").$(byText("Active")),
            inactiveTab = container.$("#navigationLeftTab").$(byText("Inactive"));

    @Step("Click 'new patient' button")
    public void clickNewPatientButton() {
        newPatientButton.click();
    }
}
```

I use this PageObject in a test like this:
```Java
@Test
public void test() {
    new PatientPage().clickNewPatientButton();
}
```

In the Allure report I see records with `activeTab` and `inactiveTab` elements which weren't accessed in the test: 
![image](https://user-images.githubusercontent.com/26544034/83267542-91e1bc80-a1ee-11ea-9903-98eda3e7dd3b.png)

#### What is the expected behavior?

`activeTab` and `inactiveTab` are unused in the test so I don't expect to see them in the report.

#### What is the motivation / use case for changing the behavior?

Correct reports.

#### Please tell us about your environment:

| Allure version | 2.13.3 |
| --- | --- |
| Test framework | selenide@5.12.1 and junit5@5.6.2 |
| Allure integration | allure-selenide@2.13.3 and allure-junit5@2.13.3 |
| Generate report using | allure-maven@2.10.0 |

**Comment by asolntsev** [comment]
@pavelnazimok It's rather a bug in Selenide. 
If you use Selenide built-in "TextReport" instead of Allure report, you will also see those unused fields:

```
+--------------------+----------------------------------------------------------------------+----------+----------+
|Element             |Subject                                                               |Status    |ms.       |
+--------------------+----------------------------------------------------------------------+----------+----------+
|open                |https://google.com/ncr                                                |PASS      |9633      |
|#patientNavigation  |$(#btnNewPatient_CD)                                                  |PASS      |88        |
|#patientNavigation  |$(#navigationLeftTab)                                                 |PASS      |0         |
|#navigationLeftTab  |$(by text: Active)                                                    |PASS      |0         |
|#patientNavigation  |$(#navigationLeftTab)                                                 |PASS      |0         |
|#navigationLeftTab  |$(by text: Inactive)                                                  |PASS      |0         |
```

@eroshenkoam This issue can be closed.

**Comment by oksanamorhunova** [comment]
I have the same issue with latest selenide 5.17.0. Can I reopen this issue?
<img width="738" alt="Знімок екрана  о 2 37 40 пп" src="https://user-images.githubusercontent.com/74051073/128701258-184bb73d-5a53-4a51-9fcc-8e994031ff37.png">
![Знімок екрана  о 2 38 58 пп](https://user-images.githubusercontent.com/74051073/128701269-2b88159d-f4e3-4d7c-820a-4e356488ce12.png)

selenide-5.17.0
testng-6.14.3
allure-testng-2.13.3
allure-selenide-2.13.2
allure-maven-2.10

**Comment by asolntsev** [comment]
Clearly, it's not an Allure issue. See the discussion in https://github.com/selenide/selenide/issues/1290#issuecomment-895222784
