### ISSUE TITLE
@Step and @Attachment annotations are not working (Java 11 or higher, Gradle 6.5, TestNG 7.1.0)

### ISSUE THREAD

**Issue by vkovalenk0** [allure-framework/allure-java#448]
#### What is the current behavior?

`@Step` and `@Attachment` annotations in code produces some strange error so test doesn't even start

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

STR: 
1) Clone this https://github.com/allure-screenshot-bug/FlightRadarTAF
2) Run ./gradlew clean build

#### What is the expected behavior?

Test is started

#### Please tell us about your environment:
|Java version| "11.0.7" 2020-04-14 LTS|
| allure-selenide | 2.13.3 |
| Test framework | testng@7.1.0 |
| Allure integration | allure-testng@2.13.3 |
| Generate report using | allure-gradle@2.8.1 |

#### Other information 

Here is stacktrace when I run with --stacktace option:
https://gist.github.com/vkovalenk0/ccf4c666b41ddfe3629c86aa8cf8ca5c

And another one in gradle test report:
https://gist.github.com/vkovalenk0/17ffc2d5ed69dbb17d1bca0cf1c3179e

**Comment by vkovalenk0** [comment]
Works well with Java 8 or when I comment Allure annotations

**Comment by baev** [comment]
you need to set AspectJ version that supports Java 11+ , it can be done via `aspectjVersion` property of Allure Gradle plugin:

```groovy
allure {
    version = '2.8.1'
    autoconfigure = true
    aspectjVersion = '1.9.5'
}
```

**Comment by vkovalenk0** [comment]
Thank you, @baev  that works for me.

I would be grateful if you or somebody else add mention of it in documentation.
For example here:
https://docs.qameta.io/allure/#_java

**Comment by vkovalenk0** [comment]
Or maybe update default version of aspectj? :)

**Comment by baev** [comment]
https://github.com/allure-framework/allure-gradle/pull/55
