### ISSUE TITLE
HttpEntity can be null in AllureHttpClientRequest

### ISSUE THREAD

**Issue by baflQA** [allure-framework/allure-java#453]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
In https://github.com/allure-framework/allure-java/blob/master/allure-httpclient/src/main/java/io/qameta/allure/httpclient/AllureHttpClientRequest.java#L68 entity can be null, e.g. when a DELETE request is sent, no entity is returned by the Http client. 
It causes NPE to be thrown in https://github.com/allure-framework/allure-java/blob/master/allure-httpclient/src/main/java/io/qameta/allure/httpclient/AllureHttpClientRequest.java#L71

#### What is the expected behavior?
NPE is not thrown. 

#### Please tell us about your environment:

| Allure version | 2.13.3 |
| --- | --- |
| Test framework | testng@7.0 |
| Allure integration | allure-testng@2.13.3 |
| Generate report using | allure-maven@2.13.3 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baflQA** [comment]
Fixing by https://github.com/allure-framework/allure-java/issues/453

**Comment by baev** [comment]
fixed by #454
