### ISSUE TITLE
Allure Rest Assured plugin does not attach Request form params in the report

### ISSUE THREAD

**Issue by loveshjain** [allure-framework/allure-java#469]
I'm submitting a ... 
  - [ ] feature request

#### What is the current behavior?
The report only attach url, method, headers, body, cookies of a request but does not attach the form params. 

https://github.com/allure-framework/allure-java/blob/master/allure-rest-assured/src/main/java/io/qameta/allure/restassured/AllureRestAssured.java#L80

#### What is the expected behavior?
The report should display form params as well or should have capability to customize what all things of a request we want in the report

#### What is the motivation / use case for changing the behavior?
My request has form params and I would like them to be displayed in report as part of the request attachment.

                      given()
				.header("content-type", "valid content type")
				.formParam("abcd", "abcd")
				.formParam("xyz", "xyz")

https://github.com/allure-framework/allure-java/blob/master/allure-rest-assured/src/main/java/io/qameta/allure/restassured/AllureRestAssured.java#L80

![image](https://user-images.githubusercontent.com/20214999/92351001-ae1ac100-f12e-11ea-8207-18ba2d35bb5e.png)

| Allure version | 2.2.0 |
| --- | --- |
| allure-rest-assured | 2.13.5 |
| Generate report using | allure-maven@2.13.5 |

#### Other information

**Comment by ristoporila** [comment]
I am looking for a way to implement this as well. Would be a useful feature.

**Comment by baev** [comment]
If you'll provide a PR I would glad to merge it

**Comment by Phoenix124** [comment]
https://github.com/allure-framework/allure-java/pull/1012

**Comment by Phoenix124** [comment]
@baev you could close this Issue due new feature https://github.com/allure-framework/allure-java/pull/1016

**Comment by baev** [comment]
fixed via https://github.com/allure-framework/allure-java/pull/1016
