### ISSUE TITLE
I cannot define the attachment name I want for the remaining Rest Assured requests and responses in the Allure Report.

### ISSUE THREAD

**Issue by ogulcanarbc** [allure-framework/allure-java#492]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a feature request
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure rest assured sets the default attachment name for the requests and responses. For the Allure report I cannot define the attachment name I want for the remaining guaranteed requests and responses.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Current behavior is not a bug 👍 

#### What is the expected behavior?
If we can make attachment names special, we will create a more understandable report. 🙏 

<img width="1495" alt="Screen Shot 2020-11-22 at 04 11 04" src="https://user-images.githubusercontent.com/26281581/99891262-09ae1280-2c79-11eb-9884-94a4d29c9e64.png">

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | Junit Jupiter@5.5.2 |
| Allure integration | allure-junit5@2.13.0|
| Generate report using | allure-maven@2.8 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by ogulcanarbc** [comment]
hi @baev , we want to use this feature, we can get new release?

**Comment by baev** [comment]
it's released in 2.13.9 (we have 2 more releases since then, the latest one is 2.14.0)

**Comment by ogulcanarbc** [comment]
thanks @baev 🙏
