### ISSUE TITLE
Skipped test steps in Allure report using allure-testng 

### ISSUE THREAD

**Issue by DmitryBrusentsov** [allure-framework/allure-java#497]
#### I'm submitting a ... 
  - [X ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
I cannot see all skipped test steps in Allure Report after a failing test step.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
I use testNG 6.14 and allure-testng adapter 2.10 with all necessary allure dependencies (all of them have versions of 2.10). Run test under this circumstances and you will see only passed or failed steps in scenario, whether test steps can be skipped also.

#### What is the expected behavior?
I expect to see skipped test steps in Allure report after a failing one, as I can see in the framework which is based on JUnit.

#### What is the motivation / use case for changing the behavior?
Testers want to see all test steps in allure report, not only passed or failed ones.

#### Please tell us about your environment:
testNG 6.14 and allure-testng adapter 2.10
| Generate report using | allure-maven@2.9 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by yaqiz16** [comment]
Any response ?

**Comment by baev** [comment]
Allure does not modify the test's behaviour. As soon as an exception is thrown, the execution stops, and no additional steps are logged. 

Allure steps should be considered as structured logs. 

The workaround to it is to use a test framework with the steps concept, e.g. cucumber. In that case, the framework may know all the expected steps and report them to Allure.
