### ISSUE TITLE
[junit5] DisplayNameGenerator is ignored for class name

### ISSUE THREAD

**Issue by scormaq** [allure-framework/allure-java#500]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?
With Junit5 it is possible to use [Display name generators](https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator) to improve test names automatically.

Allure-junit5 is supposed to print suite/test names from `displayName` value if it is available. While it works correctly for methods (`testIdentifier.getDisplayName()` is used), it does not work for classes (`@DisplayName` annotation value is looked, so values from name generator are ignored).

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Using junit5 + allure, set up DisplayNameGenerator like next:
<details>
  <summary>MyDisplayNameGenerator.java</summary>

```java
import java.lang.reflect.Method;
import org.junit.jupiter.api.DisplayNameGenerator;

public class MyDisplayNameGenerator implements DisplayNameGenerator {

    @Override
    public String generateDisplayNameForClass(Class<?> testClass) {
        return "le test suite";
    }

    @Override
    public String generateDisplayNameForNestedClass(Class<?> nestedClass) {
        return "nested class";
    }

    @Override
    public String generateDisplayNameForMethod(Class<?> testClass, Method testMethod) {
        return "test method";
    }
}
```
</details>

2. Apply it to test:
<details>
  <summary>MyTest.java</summary>

```java
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

@DisplayNameGeneration(MyDisplayNameGenerator.class)
public class MyTest {
    @Test
    void testSomething() {}

    @Nested
    class NestedClass {
        @Test
        void testAnotherThing() {}
    }
}
```
</details>

3. Execute test & generate allure report
![image](https://user-images.githubusercontent.com/6312221/102352883-06285580-3fb1-11eb-942d-04423a58f9bc.png)
*execution in IDEA to prove that generator works as expected*

![image](https://user-images.githubusercontent.com/6312221/102353324-9070b980-3fb1-11eb-9b0e-a5c808a60482.png)
*generated Allure report*

#### What is the expected behavior?
Allure should get displayed class/nested class name from provided `DisplayNameGenerator`

#### What is the motivation / use case for changing the behavior?
* Make test maintenance easier (I can supply single `DisplayNameGenerator` which will turn class or method names into human-readable sentences for example, and do not use `@DisplayName` annotations; or even apply whatever complex custom mechanizm);
* Improve allure-junit5 integration (I would like to leverage junit5 capabilities to improve my allure experience)

#### Please tell us about your environment:

| Allure version | 2.13.7 |
| --- | --- |
| Test framework | junit5@5.7.0 |
| Allure integration | allure-junit5@2.13.7 |
| Generate report using | allure-gradle@2.8.1 |

#### Other information 
N.B. Maybe it is worthy to provide, along with fix, some mechanism that will provide human-readable class/method names by default (controlled by some allure property)? IMHO it could be useful to prettify report for all the existing tests by 1 property enabled if no `displayName` provided in tests (in any way - annotations/ generators etc).

**Comment by VaclavKlic** [comment]
Hi, 
@scormaq  don't you please have some repo with this example? I ran into same problem.
IDE shows me expected result
![image](https://user-images.githubusercontent.com/92035081/186682209-422b57a6-7c16-44ba-8dc0-cde6b3e5740e.png)

But Allure report doesn't include changed test class name
![image](https://user-images.githubusercontent.com/92035081/186682395-0fd0a274-2a27-41b6-b7bd-5717cbf3c5a5.png)

My `build.gradle`  look like this
```
plugins {
    id 'io.qameta.allure' version '2.10.0' // Last Allure Plugin version
    id 'java'
}

// Allure configuration, for more info see: https://docs.qameta.io/allure#_junit_5
allure {
    autoconfigure = true
    version = '2.19.0' // Latest Allure Version

    useJUnit5 {
        version = '2.19.0' // Latest Allure Version
    }
}

group '3pg.christmasWishTests'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // JUnit
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.9.0'
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.9.0'
    // Selenium
    implementation 'org.seleniumhq.selenium:selenium-java:4.4.0'
    // WebDriverManager, for more info see: https://github.com/bonigarcia/webdrivermanager
    implementation group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.2.1'
    // MailSlurp Client
    implementation group: 'com.mailslurp', name: 'mailslurp-client-java', version: '15.13.0'
    // Allure Environment writer for setting Environment variables, for more info see: https://github.com/AutomatedOwl/allure-environment-writer
    implementation group: 'com.github.automatedowl', name: 'allure-environment-writer', version: '1.0.0'
}

test {
    useJUnitPlatform()
}
```

Do you have any idea, where I made mistake?
Thanks
