### ISSUE TITLE
Hello! How can I change default directory for allure-results? Because it has to be placed in the build directory. Because these are temporary files.

### ISSUE THREAD

**Issue by Rodion777777** [allure-framework/allure-java#501]
https://github.com/allure-framework/allure-java/blob/43a89b54aae73eab1e2852225a1a9c3329084542/allure-java-commons/src/main/java/io/qameta/allure/AllureLifecycle.java#L643

**Comment by baev** [comment]
Use `allure.properties` file in test resources with property
`allure.results.directory=build/allure-results`

**Comment by Rodion777777** [comment]
Found another way to set the parameter based on gradle. You should make in your gradle file of project this task:
```
task applyAllureProperties {
    sourceSets {
        main {
            resources {
                srcDir 'common-test-utils'
                include 'allure.properties'
                output.resourcesDir = 'src/test/resources'
            }
        }
    }
}
```
And then you must place your allure.properties file according to the path in the task.
