### ISSUE TITLE
Directory /allure-results not always created in build folder on Kotlin + Gradle + TestNg

### ISSUE THREAD

**Issue by trugaaa** [allure-framework/allure-java#505]
#### I'm submitting a ... 
  - [ ] bug report
  - [ ] feature request
  - [x] support request

#### What is the current behavior?
1) Allure documentation ( https://docs.qameta.io/allure/#_gradle_5 ) tells that
>  "After you apply automatic configuration, Allure results obtained after the test task execution will be stored in build/allure-results."

In my build.gadle.kts file i did this but /allure-results foulder is created in root project

2) I was trying to bypass it with configuration it by myself
```
allure {
    autoconfigure = true
    aspectjweaver = true
    version = allureVersion
    resultsDir = File("${buildDir}/allure-results")
}
```
But it still not works

3) I also tried to set system property 
```
tasks.withType<Test> {
    systemProperty("allure.results.directory", "${buildDir}/allure-results")
    ignoreFailures = true
    reports.html.isEnabled = false
    useTestNG {
        listeners.add("listeners.TestListener")
        suiteXmlFiles.add(File("src/test/resources/testng.xml"))
    }
    testLogging {
        showExceptions = true
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
    }
}
```
But it still creates results dir in project root

4) Last try was creating **allure.properties** file in /test/resources/ with property 
`allure.results.directory=build/allure-results`

This way results folder is created in build when i start tests with `gradle clean test` command, but when i start tests from IDEA it creates results folder still in root

Thanks for any suggestions and answers!

#### What is the expected behavior?
I want my /allure-results folder every time to be created in /build/

#### Please tell us about your environment:
| Allure version | 2.12.1 |
| --- | --- |
| Test framework | testng@7.3.0 |
| Allure integration | allure-testng@2.13.8 |
| Kotlin version | kotlin-jvm@1.4.21 |

#### Other information 
Github repo - https://github.com/trugaaa/SelenideKotlin

**Comment by baev** [comment]
thats the reason we only recommend using `allure.properties`: some IDEs ignore configuration specified in Gradle build file. Try keep only `allure.properties` (So far we experiencing no issues with it for a last few years).

**Comment by trugaaa** [comment]
> thats the reason we only recommend using `allure.properties`: some IDEs ignore configuration specified in Gradle build file. Try keep only `allure.properties` (So far we experiencing no issues with it for a last few years).

@baev, thanks for the quick answer i have one more question

if i use method with allure.properties file then:

start tests via commandline -> results are generated in build folder ✔️
start tests via testng.xml -> results are generated in build folder ✔️
start tests class with integration tests start ->  results are generated in build folder ✔️

start unit tests in classs with some functionality -> results are generated in root ❌ 

Can i define somehow allure not to generate results of unit tests in project root or just not to generate them?

**Comment by baev** [comment]
> start unit tests in classs with some functionality -> results are generated in root

the only way results generated into root is when `allure.properties` could not be found at classpath during tests run. So you can try to investigate why is that happens by reviewing your unit tests run classpath (properties loading code could be found here https://github.com/allure-framework/allure-java/blob/master/allure-java-commons/src/main/java/io/qameta/allure/AllureLifecycle.java#L641 )

**Comment by trugaaa** [comment]
Okay, after some investigation i see that i need two `allure.properties` files:
one for scr/main and second for src/test

If i have both of them then all results are stored in build/allure-results
