### ISSUE TITLE
Only single Cucumber scenario has step wise results during parallel execution.

### ISSUE THREAD

**Issue by stambecg** [allure-framework/allure-java#508]
When I am trying to execute two cucumber scenarios in parallel, only one sceanrio has step wise result created with @step annotation. 

However another has no sub steps, could you please assist to resolve this issue.

I have attached my POM file 
[Files.zip](https://github.com/allure-framework/allure-java/files/5927577/Files.zip)

and result snapshot for reference.

**Comment by baev** [comment]
I can't reproduce it using the latest version. Please create a [discussion thread](https://github.com/orgs/allure-framework/discussions/categories/questions-support) if the problem still exists.
