### ISSUE TITLE
Add support for spock 2.0 versions

### ISSUE THREAD

**Issue by verifyMe** [allure-framework/allure-java#510]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Currently allure supports spock 1.3 version

#### What is the motivation / use case for changing the behavior?
Spock 2.0 uses junit5, supports parallel test running, groovy 3.0 and other useful features. I use 2.0-M4-groovy-3.0 version and it's incompatible with allure-spock.

#### Please tell us about your environment:

| Allure version | 2.13.6 |
| --- | --- |
| Test framework | spock@2.0-M4-groovy-3.0 |
| Allure integration | allure-spock@2.13.6 |
| Generate report using | allure-gradle@2.8.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by svsik** [comment]
Hi,
I'd also love to see support for Spock 2.0 being added to allure.
I believe the creator of Spock Reports (https://github.com/renatoathaydes/spock-reports) also went through such work to adfd support for Spock 2.0 - perhaps worth to contact him in order to get more info?

**Comment by feanor777** [comment]
Would be happy to see the support of Spock as well!
Was trying to find any other way to handle this error `java.lang.NoSuchMethodError: org.spockframework.runtime.model.FeatureInfo.getDescription()Lorg/junit/runner/Description;`, but so far not successful.

**Comment by karltiirik** [comment]
https://github.com/allure-framework/allure-java/pull/830 should solve this issue
