### ISSUE TITLE
any plan for supporting karate?

### ISSUE THREAD

**Issue by auto110** [allure-framework/allure-java#540]
https://github.com/intuit/karate

**Comment by baev** [comment]
I'd like to. I didn't check 1.0 release yet, but last time it had no suitable reporting API.

**Comment by auto110** [comment]
https://github.com/ashwindbu/equi   This solution is based on karate 0.9.4. 

Now karate1.0.0 is a big upgrade, maybe the time is mature to support the karate. The creator of the karate has fully consideration on supporting custom report solution.

**Comment by QATew** [comment]
Any plan to integrate this?
