### ISSUE TITLE
Allure report with rest assured data

### ISSUE THREAD

**Issue by vikyad** [allure-framework/allure-java#55]
Hi,

I am not getting the allure report in HTML format and I tried to add the dependency to maven, which is not taking up.So I imported the project and build it using gradle, which is giving me results in son format in  build/allure-results. So I have two problems as stated below:

1> How to get the allure report in html format.
2> How to get the allure report with rest assured data as shown in the url : https://github.com/allure-framework/allure-java/pull/51 with maven project.

**Comment by baev** [comment]
> 1> How to get the allure report in html format.

See docs https://docs.qameta.io/allure/2.0/#_reporting 

> 2> How to get the allure report with rest assured data as shown in the url : #51 with maven project.

It is not ready yet

**Comment by vikyad** [comment]
Thanks,
Vikas

**Comment by vikyad** [comment]
Hi,

Thanks for the help, but still I am not able to get the report. In gradle
project which you have developed and is available in the git, can I get the
allure rest assured report as shown in
https://github.com/allure-framework/allure-java/pull/51.

Thanks
Vikas

**Comment by vikyad** [comment]
Hi,

I am getting the allure-results in json format and whenever i am running allure generate command it is giving me no allure results. Can you please suggest anything for this.

Thanks,
Vikas

**Comment by baev** [comment]
make sure you have allure-commandline version 2.0.1 installed. To check the version simply run `allure --version`.

Then to view the report run `allure generate path/to/allure-results`. If no luck make sure that allure-results folder contains some non-empty json files with names ends with `results.json`

For more details see the docs https://docs.qameta.io/allure/2.0/

**Comment by vikyad** [comment]
Hi,
I appreciate the help and instant replies to my queries and here i am with one more.
I download allure-commandline from the link which you provided : 
> https://docs.qameta.io/allure/2.0/
> 
But still ./allure version is giving 1.5.2
I want to get the request/response in my allure report and nothing is working. 
Can you please help me regarding this.
I am using mac os.
Thanks,
Vikas

**Comment by vikyad** [comment]
Hi,

With allure-commandline 2.0 i am getting the report. Thanks for the help, but still i am not getting rest assured request response. I have included the jars of allure-rest assured and allure-retrofit, but still i am not getting the request response.

Thanks,
Vikas

**Comment by vikyad** [comment]
Hi,

How to get the rest assured log in my allure report as shown in the the
screen shots in the link :
https://github.com/allure-framework/allure-java/pull/51

Thanks
Vikas

**Comment by eroshenkoam** [comment]
@vikyad It's under developing right now. You can't generate report with rest-assured log before #51 will be closed and merged to master.

**Comment by vikyad** [comment]
Hi,

I appreciate the help and instant replies to my queries.

Thanks,
Vikas
