### ISSUE TITLE
Is deprecation in Allure 3.0 still considered?

### ISSUE THREAD

**Issue by split-n** [allure-framework/allure-java#551]
io.qameta.allure.model.ExecutableItem is deprecated since #249 3 years ago.

https://github.com/allure-framework/allure-java/blob/d1311ab485873fe7b21d35b41cc74a70c03d6702/allure-model/src/main/java/io/qameta/allure/model/ExecutableItem.java#L28

I want to use its inherited class (TestResult) but its inherited method is also deprecated due to parent class is deprecated.
Is the deprecation still alive? What is the plan for Allure 3.0? Is there any alternatives?

**Comment by baev** [comment]
ExecutableItem is deprecated, it will be replaced with interface. 

> but its inherited method is also deprecated due to parent class is deprecated

Not exactly true, simply use methods on TestResult instead of ExecutableItem, eg TestResult::getName instead of ExecutableItem::getName

**Comment by split-n** [comment]
Thanks!
