### ISSUE TITLE
Priorities break after upgrading to 2.13.9

### ISSUE THREAD

**Issue by spatiumstas** [allure-framework/allure-java#553]
**Describe the bug**
Priorities were broken after upgrading to version 9, tests are run in random order, ignoring the priority parameter

**To Reproduce**

1. Run tests with parameter priority, example:
"@Test(testName = "Check popup for withdraw funds", priority = 1) 
@Test(testName = "Check....", priority = 2)"

2. Run on 2.13.8 and run on 2.13.9

**Expected behavior**
On 2.13.8 we have first priority 1, then the priority 2
On 2.13.9 we have first priority 2, then the priority 1 or another random priorities 

Selenide Version: 5.20.1
Chrome\Firefox\IE Version: 89 Chrome
Browser Driver Version: 4.3.1
Selenium Version: 3.141.59

**Comment by baev** [comment]
@spatiumstas could you please specify the test framework and version you're using?

**Comment by spatiumstas** [comment]
Edited

**Comment by baev** [comment]
@spatiumstas am I right that `@test` annotation with priority comes from TestNG?

**Comment by spatiumstas** [comment]
> @spatiumstas am I right that `@test` annotation with priority comes from TestNG?

Yes, forgot to mention

**Comment by s-panchenko** [comment]
I have the same issue.

**Comment by raulcabero** [comment]
same issue

**Comment by pwebster-cpi** [comment]
My tests also starting running out-of-order after upgrading to Allure 2.13.9. Downgrading to 2.13.8 restored the correct test order.  I'm using TestNG 7.3.0 with Surefire plugin 3.0.0-M4.
