### ISSUE TITLE
[allure-cucumber6-jvm] Missing test cases in a report for features with same filenames.

### ISSUE THREAD

**Issue by algirdasN** [allure-framework/allure-java#570]
**Describe the bug**
Executing multiple feature files with same filenames in a single suite causes some of the results to be missing. This can be clearly seen in fragmented Allure timeline.

Looking at the generated results each test has a container.json file, however, some of them are missing results.json. Looking into more detail, tests with same feature filename have identical child UUID. This probably causes the results to be overwritten.

**To Reproduce**
Please use my mock test suite - https://github.com/algirdasN/Allure_bug_replication
1. run tests using maven - 'mvn clean test'
2. create allure test - 'allure serve .\target\allure-results'

**Expected behavior**
Each test case should be in the report.

**Screenshots**
![image](https://user-images.githubusercontent.com/61432976/116400016-38d13d00-a832-11eb-84e9-5ad607a96d88.png)

![image](https://user-images.githubusercontent.com/61432976/116400185-6cac6280-a832-11eb-8aa6-bd15923b5181.png)

![image](https://user-images.githubusercontent.com/61432976/116400685-0247f200-a833-11eb-86ba-ab12301586ba.png)

![image](https://user-images.githubusercontent.com/61432976/116400726-0aa02d00-a833-11eb-8605-2592d98f922c.png)

![image](https://user-images.githubusercontent.com/61432976/116400754-112ea480-a833-11eb-8ad9-d40c1e68219a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: latest

**Comment by anirbandan** [comment]
Hi @baev 
I am experiencing a similar behaviour with allure-ruby. 
Do you know if this issue exists there?
I am using allure-rspec gem version 2.18.0
