### ISSUE TITLE
Fails to discover tests with Java16 (Allure 2.14.0/Junit5)

### ISSUE THREAD

**Issue by frode-carlsen** [allure-framework/allure-java#589]
**Describe the bug**
Allure fails to discover tests under Java 16 with latest Aspectjweaver

**To Reproduce**
Migrated working build running with junit5 (as per https://docs.qameta.io/allure/#_junit_5) and java 15,
this fails under java 16.  
First, because it requires ASM 9.1 for class file compatibliity. This is bundled in the javaagent Aspectjweaver. However Aspectjweaver 1.9.6 comes with ASM 8.  
Upgrading Aspectjweaver to 1.9.7.M2 still fails, but due to the following error:

`Error:  TestEngine with ID 'junit-jupiter' failed to discover tests`

With Aspectjweaver 1.9.6 it fails with the following:
`
AspectJ Internal Error: unable to add stackmap attributes. Unsupported class file major version 60
java.lang.IllegalArgumentException: Unsupported class file major version 60
	at aj.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
Error:  TestEngine with ID 'junit-jupiter' failed to discover tests
`
**Expected behavior**
That it finds tests

**Screenshots**

**Desktop (please complete the following information):**
- Github Action, basic ubuntu runner

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kriegaex** [comment]
This issue can be closed, it is not an Allure or AspectJ problem, but the user tried to run classes compiled with JDK 15, using preview features, on JDK 16. I explained everything in detail in https://github.com/eclipse/org.aspectj/issues/45#issuecomment-848375087 and https://github.com/eclipse/org.aspectj/issues/45#issuecomment-848383141.
