### ISSUE TITLE
Link TestResult to JUnit platform TestIdentifier 

### ISSUE THREAD

**Issue by naresha** [allure-framework/allure-java#593]
**Is your feature request related to a problem? Please describe.**
I am trying to implement `TestLifecycleListener` in which I need to identify from the `TestResult` object to which test it corresponds. JUnit Platform uses `TestIdentifer` for uniquely identifying the tests. Hence I would like to be able to navigate from `TestResult` to `TestIdentifier`.

**Describe the solution you'd like**
Add a String field to `TestResult` to store the value obtained by invoking `toString()` on `org.junit.platform.engine.UniqueId` obtained from the `TestIdentifier` instance. 
`TestResult` has a field `testCaseId` which doesn't seem to be used for other purposes at the moment. Hence I believe we could make of that field for this purpose. Please suggest.

**Comment by baev** [comment]
fixed via #594
