### ISSUE TITLE
Requesting Flag for including/ignoring configuration failures in Allure report

### ISSUE THREAD

**Issue by umashankar51** [allure-framework/allure-java#623]
**Problem:**
When before/after configuration steps fails, they are counted as test case failures in the final allure report. 

**Required/Suggested solution:**
Add a condition in the onConfigurationFailure method which decides if and what before/after configuration steps are to be included in allure report based on flag values set in 'allure.properties'. We can allow current behavior to continue if property file is not found or if properties are set to default.

**Alternatives:**
For now, we have implemented our own listener mimicking the AllureTestNg listener while ignoring configuration failures

**Additional context:**
It makes reporting difficult, we had to give a manual report of configuration failures vs test failure. It is difficult and requires a lot of effort to revisit 500+ test cases and handle exception on the configuration steps. Hence this request. This change will be useful for other allure users as well.

**Comment by tomkeiev** [comment]
#920
