### ISSUE TITLE
Add public methods or annotation for custom listeners registration

### ISSUE THREAD

**Issue by ASaunin** [allure-framework/allure-java#63]
There might be a great opportunity to customize own `ContainerLifecycleListener`, `FixtureLifecycleListener`, `StepLifecycleListener` and `TestLifecycleListener` listeners. 
At a present moment is possible to implement these interfaces, but there is no method to register them for the `LifecycleNotifier`

**Comment by sskorol** [comment]
These listeners are SPI. So first you have to implement them. The second step is creating a file named by one of implemented interfaces in your project's `resources/META-INF/services` folder, e.g. `io.qameta.allure.listener.StepLifecycleListener`. This file should contain a full path to the class, which implements corresponding interface. You can find more in official SPI docs.
