### ISSUE TITLE
HistoryId for failed tests which use non primitive DataProvider is not correct.  

### ISSUE THREAD

**Issue by bgalamb** [allure-framework/allure-java#644]
**Describe the bug**
Allure testNG plugin generates wrong history id for tests which use Dataprovider and fail. These tests contain the Dataprovider's object unique(memory) Id as one of the parameters. Because this ID is always different a new test run of the  test will never be linked to the failed one. After each rerun, the number of total tests is going to increase but the original failed one will never be "replaced" by the successful one. Sample projects to reproduce:
1- this helps to reproduce
[bug_reports2.zip](https://github.com/allure-framework/allure-java/files/7077045/bug_reports2.zip)

**To Reproduce**
1. Open bug_reports2.zip
2. execute `mvn clean test`
3. go to `target` execute `allure serve`
4. See agr0 parameters for all data provider tests

**Expected behavior**
I would not see java objectIds in the parameters as these are not going to be linked correctly with history of the same test case ( because the overall string is always unique)

I have prepared fix by modifying method protected String getHistoryId() in io/qameta/allure/testng/AllureTestNg.java in attached sample project.
[bug_reports3.zip](https://github.com/allure-framework/allure-java/files/7077076/bug_reports3.zip)
1. Open bug_reports3.zip
2. execute `mvn clean test`
3. go to `target` execute `allure serve`
4. See agr0 parameters for all data provider tests does not have objectId thus historyId is correct.

**Screenshots**
<img width="1903" alt="Screenshot 2021-08-30 at 15 34 37" src="https://user-images.githubusercontent.com/14314062/131347600-ca8a6a26-9ecd-4780-b5cb-3fc67ba659ce.png">

===expected screenshot===
<img width="1903" alt="Screenshot 2021-08-30 at 15 41 33" src="https://user-images.githubusercontent.com/14314062/131348610-80d8560d-f804-4075-a974-f3c054d952c1.png">

**Desktop (please complete the following information):**
 - OS: [MAC]
 - Browser [Chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by baev** [comment]
Allure uses `Object#toString` to get string representation of parameter's value. If no `toString` is provided, it defaults to `getClass().getName() + '@' + Integer.toHexString(hashCode())`.  So, implementing `toString` on your DataProvidedTest1$MyData class will fix the issue
