### ISSUE TITLE
Request and response in allure report

### ISSUE THREAD

**Issue by vikyad** [allure-framework/allure-java#65]
Hi,

I am trying to get the rest assured request/response in my allure report in Testng. Please guide me to get it done.

Regards
Vikas

**Comment by baev** [comment]
This feature is still under construction, the docs will be available here https://docs.qameta.io/allure/2.0/ as soon as it will be ready

**Comment by mf-ooyala** [comment]
@baev what about docs? thanks

**Comment by mufasa1** [comment]
@baev  Hi, have you added this feature? For logging request and response in Reporting. Thanks. And could you please show the way to use this feature?

**Comment by lmangoua** [comment]
@mufasa1 Hi,
did you find a way to display the request/response in your report?

**Comment by marisita** [comment]
@baev Hi, have you released this feature and docs for it? Thanks.

**Comment by baev** [comment]
@marisita yep, the feature is implemented, we have multiply integrations with http clients (jax-rs, rest-assured, servlet-api, apache http client, okhttp). In general, all you need is add dependency and configure request/response interceptors. 

Unfortunately we have no docs for this feature yet, only a short notes in project readme, see https://github.com/allure-framework/allure-java#okhttp

**Comment by marisita** [comment]
@baev thank a lot for your reply! And what about #51 feature? (https://github.com/allure-framework/allure-java/pull/51)

**Comment by baev** [comment]
yep, retrofit uses okhttp under the hood, rest assured is also available

https://github.com/allure-framework/allure-java#okhttp
https://github.com/allure-framework/allure-java#rest-assured

**Comment by attitudeizeverything** [comment]
@baev Can you please show an example of how and where to configure request\response interceptors? Created tpl folder under resources, but not sure what to do next

I added all dependencies and codes for attachments, but unable to understand where to add this usage example:

.filter(new AllureRestAssured())
AND
.filter(new AllureRestAssured()
        .withRequestTemplate("custom-http-request.ftl")
        .withResponseTemplate("custom-http-response.ftl"))

**Comment by chunji08** [comment]
I have the same question, can someone present a clear example. Thanks.

**Comment by marisita** [comment]
Hi @chunji08, to attach http requests/responses to allure report try to add the next code before first call of rest-assured methods:
RestAssured.requestSpecification = new RequestSpecBuilder().build().filter(new AllureRestAssured());

**Comment by Biloleg** [comment]
Error:(21, 24) java: cannot access io.restassured.filter.OrderedFilter
  class file for io.restassured.filter.OrderedFilter not found

**Comment by nikhila294** [comment]
Hi , Any updates on rest assured request/response in allure report??

**Comment by mmakare** [comment]
> 

I have the same issue. Have you solved it?

**Comment by cheshi-mantu** [comment]
@dsalokin pls add to plans for the update of allure fw docs
