### ISSUE TITLE
Custom AssertJ integration with Allure

### ISSUE THREAD

**Issue by pandoras-toolbox** [allure-framework/allure-java#680]
I use allure-assertj dependency in order to see the AssertJ assertions in the test report.

There are situations where I want to use an AssertJ method but do not want to include that assertion into the Allure report. Is that possible and how?

And there are other situations where I want to include the AssertJ assertions in the report, but shorten the strings if they are too long, because they might be very big. Is that possible?

**Comment by baev** [comment]
you can create your own aspect for that. See https://github.com/allure-framework/allure-java/blob/master/allure-assertj/src/main/java/io/qameta/allure/assertj/AllureAspectJ.java as an example

**Comment by pandoras-toolbox** [comment]
I will ask a developer how to make that work, because when I copied and pasted it and put it into our project it did not stop at the breakpoints in that class.

**Comment by baev** [comment]
you may also need to register aspect using `aop.xml`. See https://github.com/allure-framework/allure-java/blob/master/allure-assertj/src/main/resources/META-INF/aop-ajc.xml

**Comment by pandoras-toolbox** [comment]
That did the trick, thank you! I think I will be able to implement now what I intend.

Instead of "assertThat" I used "assumeThat" and hoped that I can solve my issue with it easily, that it will be ignored for the Allure report. But it is not ignored, which seems to make sense. But I think the step name is in any case "assertThat" even if it might be an "assumeThat". No big deal, I just noticed it.

**Comment by muja** [comment]
Hi I just want to add because I found this issue and just spent a good 3 hours trying to get it to work. My problem was that in the top-level some `<weaver>` instructions limited the weaving to specific libraries. If that's the case, you'll want to add a `<weaver within="org.assertj.core..*" />` in there.
