### ISSUE TITLE
Аллюр не отображает timeline-бары всех выполненных тестов в многопоточном запуске

### ISSUE THREAD

**Issue by dm-test** [allure-framework/allure-java#708]
**Describe the bug**
В стеке Java temurin-11 + Junit5 + Cucumber7 при запуске тестов в многопоточном режиме на таймлайне "теряются" тесты в следующем кейсе: 
допустим, есть 3 теста, которые запускаются в 2 потока. В этом случае в отчете на странице "timeline" мы увидим только 2 timeline-бара, но в шапке на этой же странице будет указано, что тестов было 3 штуки.

**To Reproduce**
Для воспроизведения создал простой проект: https://github.com/dm-test/junit5-cucumber-spring-allure-example
1. запустить тесты командой mvn clean test
2. сформировать отчет командой mvn allure:serve
3. перейти на страницу "timeline"

**Expected behavior**
На странице отображаются timeline-бары 3 запущенных тестов

**Screenshots**
![image](https://user-images.githubusercontent.com/34338773/150335011-d63ccf8d-5db0-4ca4-bc8d-3ffa054682f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97.0.4692.71

**Comment by baev** [comment]
only issues created in english language are allowed. Before raising an issue please consider getting the help using our support channels (https://github.com/orgs/allure-framework/discussions or community chats)
