### ISSUE TITLE
AllureCucumber4Jvm does not recognise rerun scenarios

### ISSUE THREAD

**Issue by Hamzaan-Bridle** [allure-framework/allure-java#715]
**Describe the bug**
AllureCucumber4Jvm  does not recognise rerun scenarios. The `uuid` caching of the scenario means that reruns replace the test result of the original run. The breaks the Allure "Retries" and "Flaky" features.

**To Reproduce**
1. Run cucumber tests using a test runner that can retry (e.g. TestNG)
2. Have one or more tests that fail and retry
3. Allure report shows only one test result for the flaky scenario

**Expected behavior**
All test runs visible in the Allure report

**Screenshots**
Expected behaviour:
<img width="962" alt="Expected" src="https://user-images.githubusercontent.com/93982055/156749037-ade6a123-81a7-4e35-9969-ac32052bd832.png">

Actual behaviour:
<img width="960" alt="Actual" src="https://user-images.githubusercontent.com/93982055/156749034-fd88c49e-252c-4256-ac54-68298765a2d3.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: allure-cucumber4-jvm:2.17.3

**Comment by Hamzaan-Bridle** [comment]
I have a code fix for this, just creating the issue to tag in the PR 🙂

**Comment by baev** [comment]
retries work as expected, tested with the latest release (Allure 2.26.0, Maven + JUnit Platform + CucumberJVM 7)
