### ISSUE TITLE
Step/Attachment are not shown in the report if they are added by a custom thread.

### ISSUE THREAD

**Issue by tbarabanov** [allure-framework/allure-java#717]
**Describe the bug**
I've tried to write a simple interceptor which adds steps and attachments to allure report on message send and received events. Found that it worked time to time depending on how my tests are written. I've investigated the behaviour as much as I could and find out following - see the code snippet:

**To Reproduce**
`
public class Tt4 {
    
    Thread t;

    @BeforeClass
    public void beforeClass() throws InterruptedException {
        t = new Thread(() -> {
            while (true) {
                try {
                    Thread.sleep(100);
                    step("123", () -> attachment("attach", "content"));
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
        });
        t.start();
        Thread.sleep(10000);
        t.interrupt();
    }

    @AfterClass
    public void afterClass() {
//        t.interrupt();
    }

    @Test
    public void t() throws InterruptedException {
        Thread.sleep(10000);
    }
}
`

If I start the thread and interrupt it in the beforeClass (or start/interrupt in the test t()) method, the step will be in the report, but if I  interrupt it in, for instance, afterClass, then no step/attachment will be shown. Json file in the allure-report with attachment is generated, but not linked to the results. 

**Expected behavior**
I'm not sure if it should work this way.  Anyway it would be nice to see steps/attachments in the report.

allure version 2.17.3
testng version 7.5 (tried other versions with the same results)
macos 12.2.1

**Comment by mcsymiv** [comment]
Is there a resolution to this problem? I am facing similar issue in my automation as well.

**Comment by baev** [comment]
you can only interact with Allure Context within a thread that started the context (in general, reporter thread) and it's children. Otherwise you need to pass parent step uuid manually to `io.qameta.allure.AllureLifecycle#startStep(java.lang.String, java.lang.String, io.qameta.allure.model.StepResult)`.

In order to get parent step uuid you can use `io.qameta.allure.AllureLifecycle#getCurrentTestCaseOrStep` and to set thread context you can use `io.qameta.allure.AllureLifecycle#setCurrentTestCase`

**Comment by mcsymiv** [comment]
@baev, thank you, it worked
