### ISSUE TITLE
Как отключить фейковые результаты из аллюр-отчёта и результаты с падением в прекондишн?

### ISSUE THREAD

**Issue by traarttra** [allure-framework/allure-java#761]
**Описание**
1. При запусках по сьюту ТестНГ или по группам, отключенные тесты попадают в отчёт со статусом Unknown;
2. Если тест упал в прекондишн, то в отчёте дублируется вывод этого теста.

**Ожидания**
- Выключенные тесты(с помощью аннотации Ignore или параметра enabled = false) не отображаются в отчёте;
- Тесты, которые упали в прекондишен не дублируются в отчёте.

**Фоточки**
![image](https://user-images.githubusercontent.com/18459337/170266493-904cca8e-7ac9-42c5-8069-33616df4c13c.png)

**Версии библиотек:**
 - allure: 2.17.3;
 - selenide: 5.25.0-selenium-4.0.0;
 - testng: 7.5

**Дополнительная инфа**
Хочу узнать, есть ли возможность отключить эти параметры вывода опционально в отчёт? Пытались переопределить метод onStart(ITestContext context) класса AllureTestNG, в котором исключили использование метода createFakeResult, но это не помогло.

**Comment by baev** [comment]
only issues created in english language are allowed. Before raising an issue please consider getting the help using our support channels (https://github.com/orgs/allure-framework/discussions or community chats)
