### ISSUE TITLE
Java 17 + allure-junit5 (2.18.1) в отчет перестали попадать Step и Attachment

### ISSUE THREAD

**Issue by TaosKDV** [allure-framework/allure-java#763]
После перехода на java 17 и обновления allure (allure-junit5) на последнюю версию «2.18.1» в отчет перестали попадать Step и Attachment. При этом AllureId, Story, Feature, DisplayName в отчет попадают.

[TestAndResult.zip](https://github.com/allure-framework/allure-java/files/8779084/TestAndResult.zip)

**Comment by cheshi-mantu** [comment]
Please use following settigs for maven. 

[pom.xml.zip](https://github.com/allure-framework/allure-java/files/8785722/pom.xml.zip)
