### ISSUE TITLE
Screenshot is not attached to Allure when executing it in beforeTestStop() method.

### ISSUE THREAD

**Issue by muarts** [allure-framework/allure-java#813]
**Describe the bug**
I want to attach the screenshot of failed test to the Allure report. I used TestNG's ITestListener interface's onTestFailure() method first and see the attachment file is visible in the allure-results folder yet not visible in the report itself. After that, I implement the solution suggested here: https://github.com/allure-framework/allure-java/issues/444
The attachment file is not visible both in the allure-results folder and report itself.  When I debugged I saw that it executes the onTestFailure() method but beforeTestStop() is not executed.

You can see my implementation below.

```
public class TestListener implements ITestListener, TestLifecycleListener {

    ThreadLocal<WebDriver> drivers = new ThreadLocal<>();

    @Override
    public void onTestStart(ITestResult result) {
        System.out.printf("Test started: %s\n", result.getName());
    }

    @Override
    public void onTestSuccess(ITestResult result) {
        System.out.printf("Test passed: %s\n", result.getName());
    }

    @Override
    public void onTestFailure(ITestResult result) {
        System.out.printf("Test failed: %s\n", result.getName());
        WebDriver driver = ((BaseTest) result.getInstance()).getDriver();
        drivers.set(driver);
    }

    @Override
    public void beforeTestStop(TestResult result) {
        if(result.getStatus().name().equalsIgnoreCase("FAILED")) {
            takeScreenshot(drivers.get());
        }
    }

    private void takeScreenshot(WebDriver driver) {
        Allure.addAttachment("Screenshot of failed step", new ByteArrayInputStream(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES)));
    }

    @Attachment(value = "Page screenshot", type = "image/png")
    private byte[] saveScreenshot(WebDriver driver) {
        byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
        return screenshot;
    }

}

```
**Expected behavior**
I want to see the screenshot of failed test in the Allure report.

**Comment by michalw666** [comment]
I have the same issue with beforeTestStop() method. Please advice.

<html>
<body>


Allure version | 2.19.0
-- | --
Test framework | testng@7.6.1
Allure adaptor | allure-testng@2.19.0
Generate report using | allure-maven@2.11.2


</body>
</html>

**Comment by calvario-31** [comment]
I have the same issue... try to ge the screenshot on test start but on both cases says the same log message:
```
[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running
[main] ERROR io.qameta.allure.AllureLifecycle - Could not add attachment: no test is running
```
Maybe is related to the browser version? I run on a previous framework I have locally and it also didnt get the screenshot (same error) even if they have old dependencies and previously was working

Allure version | 2.19.0
-- | --
Test framework | testng@7.6.1
Allure adaptor | allure-testng@2.19.0
Generate report using | allure-maven@2.11.2

**Comment by SoLsysTeMus** [comment]
I have the same issue

Allure version | 2.19.0
-- | --
Test framework | testng@7.5
Allure adaptor | allure-testng@2.19.0
Generate report using | allure-maven@2.11.2

**Comment by calvario-31** [comment]
> **Describe the bug** I want to attach the screenshot of failed test to the Allure report. I used TestNG's ITestListener interface's onTestFailure() method first and see the attachment file is visible in the allure-results folder yet not visible in the report itself. After that, I implement the solution suggested here: #444 The attachment file is not visible both in the allure-results folder and report itself. When I debugged I saw that it executes the onTestFailure() method but beforeTestStop() is not executed.
> 
> You can see my implementation below.
> 
> ```
> public class TestListener implements ITestListener, TestLifecycleListener {
> 
>     ThreadLocal<WebDriver> drivers = new ThreadLocal<>();
> 
>     @Override
>     public void onTestStart(ITestResult result) {
>         System.out.printf("Test started: %s\n", result.getName());
>     }
> 
>     @Override
>     public void onTestSuccess(ITestResult result) {
>         System.out.printf("Test passed: %s\n", result.getName());
>     }
> 
>     @Override
>     public void onTestFailure(ITestResult result) {
>         System.out.printf("Test failed: %s\n", result.getName());
>         WebDriver driver = ((BaseTest) result.getInstance()).getDriver();
>         drivers.set(driver);
>     }
> 
>     @Override
>     public void beforeTestStop(TestResult result) {
>         if(result.getStatus().name().equalsIgnoreCase("FAILED")) {
>             takeScreenshot(drivers.get());
>         }
>     }
> 
>     private void takeScreenshot(WebDriver driver) {
>         Allure.addAttachment("Screenshot of failed step", new ByteArrayInputStream(((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES)));
>     }
> 
>     @Attachment(value = "Page screenshot", type = "image/png")
>     private byte[] saveScreenshot(WebDriver driver) {
>         byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
>         return screenshot;
>     }
> 
> }
> ```
> 
> **Expected behavior** I want to see the screenshot of failed test in the Allure report.

I made it to work on this repo https://github.com/calvario-31/SeleniumJavaCompleteFramework/blob/main/src/main/java/listeners/AllureListeners.java but had to use a static driver

**Comment by baev** [comment]
see https://github.com/allure-framework/allure-java/issues/707#issuecomment-1083340458
