### ISSUE TITLE
Test name duplicated in the report

### ISSUE THREAD

**Issue by iNikem** [allure-framework/allure-java#831]
I have the following simple JUnit test:
```
  @RepeatedTest(value = 2, name = RepeatedTest.LONG_DISPLAY_NAME)
  @DisplayName("Long name")
  public void repeatLong() {
    Assertions.assertTrue(true);
  }

  @RepeatedTest(value = 2, name = RepeatedTest.SHORT_DISPLAY_NAME)
  @DisplayName("Short name")
  public void repeatShort() {
    Assertions.assertTrue(true);
  }
```

Here how does the Allure report for it looks like:
<img width="804" alt="Screenshot 2022-10-20 at 10 38 00" src="https://user-images.githubusercontent.com/3010154/196886252-47145db3-06db-4622-9aea-62a7ae99d111.png">

As you can see, name of the `repeatLong` test method has duplicated portion in it. I expect the name to be "Long name :: repetition 1 of 2" instead of "Long name Long name :: repetition 1 of 2".

For reference, this is how test names look in IntelliJ IDEA:
<img width="413" alt="Screenshot 2022-10-20 at 10 40 17" src="https://user-images.githubusercontent.com/3010154/196886704-ed1f125b-2c34-455b-aaf8-9b4e2d03d112.png">

and in gradle html report:
<img width="461" alt="Screenshot 2022-10-20 at 10 40 48" src="https://user-images.githubusercontent.com/3010154/196886843-e00fee01-8cec-47b0-aa11-c4a698048b87.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser: Safari 15.6.1

JUnit version 5.8.1, Gradle Allure plugin 2.11.0

**Comment by baev** [comment]
Allure always adds `{displayName}` for all tests of type `test-template-invocation` (ParameterizedTest, RepeatedTest etc). That way test names are more readable in Allure for users who uses default configuration.

**Comment by iNikem** [comment]
But don't you agree that in this case the end result is bad?

**Comment by baev** [comment]
from UX point of view, default behaviour is much more important. Users who change the defaults are usually have more experience and can tune report to achieve whatever behaviour they want. 

My personal opinion on that is that design of *short names* in JUnit 5 is a mistake. And now everyone is trying to workaround it in reporting, logging etc. Even IDEA removes prefix of name if it starts with name of parent. 

Allure will support infinite groupings and report correct execution trees someday, but so far it is as it is. Do you have any suggestions how it supposed to be implemented in the first place?
