### ISSUE TITLE
Usage example allure-assertj and allure-hamcrest

### ISSUE THREAD

**Issue by perkele99** [allure-framework/allure-java#833]
can I ask for usage example allure-assertj and allure-hamcrest?

**Comment by baev** [comment]
1. add [allure-assertj](https://mvnrepository.com/artifact/io.qameta.allure/allure-assertj) to classpath
2. make sure AspectJ is configured (part of regular configuration, done automatically by allure-gradle)
3. use asserts as usual

For example, we use it for our tests as well, this assert https://github.com/allure-framework/allure-java/blob/master/allure-junit-platform/src/test/java/io/qameta/allure/junitplatform/AllureJunitPlatformTest.java#L525-L533 is displayed like this in the report:

<img width="765" alt="Screenshot 2022-10-24 at 20 21 35" src="https://user-images.githubusercontent.com/2149631/197535866-56693464-5a6b-4df6-b336-4f58c266de5c.png">

PS for allure-hamcrest all the same, dependency + AspectJ
