### ISSUE TITLE
Duplicated test results in the report

### ISSUE THREAD

**Issue by Sharmi34** [allure-framework/allure-java#870]
Getting duplicated test results for allure-cucumber when allure-junit is used

Steps to reproduce the behavior:I
1. Add both allure-junit5 and allure-cucumber7-jvm maven dependency in pom.xml
2. Use maven-failsafe-plugin for integration test (uses cucumber bdd)
3. Run mvn clean verify
4. Duplicated results will be generated in allure report (one by allure-cucumber7-jvm and one by allure-junit5)

<img width="411" alt="image" src="https://user-images.githubusercontent.com/40237335/210977820-4b5c7249-22ea-4c28-91f5-f20619e9d4a9.png">

My investigation is that as the cucumber uses junit runner , when we add allure-junit5 dependency - that also run the cucumber test case.

**Comment by cheshi-mantu** [comment]
hi,
this is actually correct behaviour.
You need to exclude junit5 dependency

**Comment by baev** [comment]
Fixed via https://github.com/allure-framework/allure-java/pull/947
