### ISSUE TITLE
Spock2 BDD blocks not appearing

### ISSUE THREAD

**Issue by alexmjames** [allure-framework/allure-java#871]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

I am having spock2 tests alone in a project with below surefire config and dependencies in pom. The allure report generated is not having the given-when-then blocks as expected with allure-spock2 implementation but rest of the details like steps, attachments etc are available. Am I missing any configuration/dependency or is this a bug.

```
 <build>
      <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>3.0.0-M7</version>
          <dependencies>
            <dependency>
              <groupId>org.aspectj</groupId>
              <artifactId>aspectjweaver</artifactId>
              <version>1.9.9.1</version>
            </dependency>
          </dependencies>
          <configuration>
            <useModulePath>false</useModulePath>
            <useFile>false</useFile>
            <argLine>-javaagent:${settings.localRepository}/org/aspectj/aspectjweaver/1.9.9.1/aspectjweaver-1.9.9.1.jar</argLine>
            <includes>
              <include>**/*Spec*.*</include>
            </includes>
          </configuration>
     </plugin>
     <plugin>
        <groupId>org.codehaus.gmavenplus</groupId>
        <artifactId>gmavenplus-plugin</artifactId>
        <version>2.1.0</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compileTests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
 </build>
 <dependencies>
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>2.3-groovy-3.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.qameta.allure</groupId>
      <artifactId>allure-spock2</artifactId>
      <version>2.20.1</version>
      <scope>compile</scope>
    </dependency>
 </dependencies>
```
     

#### What is the expected behavior?
Allure report having Given-When-Then blocks with the associated comments like

```
given: set the query params
..
when: call get method
..
then: check the response status code
```

#### Please tell us about your environment:

| Allure version | 2.20.1 |
| Test framework | spock-core@2.3-groovy-3.0 |
| Allure integration | allure-spock2@2.20.1 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
See https://github.com/allure-framework/allure-java/issues/928#issuecomment-1594596412
