### ISSUE TITLE
Add Cucumber Scenario URI together with line number inside reports

### ISSUE THREAD

**Issue by fslevoaca-ionos** [allure-framework/allure-java#876]
Hi, 
Right now, the only Cucumber scenario path we get inside the Allure reports is made from Feature name and Scenario name:

![image](https://user-images.githubusercontent.com/100419179/215503522-5ff4341e-26d8-484b-a2ca-7ee6cf0b38cc.png)
```
Restore snapshot with redirect: Reapply with different target
```
not much I can do with this path, unless I take the scenario name and search by it inside my Cucumber features project directory.

It is much more practical if we include the Scenario URI together with the corresponding line number from the feature file:

```
features/Snapshot/RestoreSnapshotWithRedirect.feature:9
```
This way I can copy and paste the path from above directly inside Search dialog of the IDE, and cursor will also be set directly on that line number

Cucumber already offers support for Scenario URI and Line number.

**Comment by baev** [comment]
fixed in https://github.com/allure-framework/allure-java/pull/947
