### ISSUE TITLE
Support JUnit Display Name Generator

### ISSUE THREAD

**Issue by wazzeps** [allure-framework/allure-java#919]
**Is your feature request related to a problem? Please describe.**

Currently, allure takes class and method names from @DisplayName annotation (JUnit 5).

This may cause redundant code to be generated when integrating multiple services.
For example, if test method names are taken from an another service, @DisplayName annotation is still required to generate a readable report.

**Describe the solution you'd like**

Implement supporting of DIsplay Name Generator
https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator

**Comment by a-simeshin** [comment]
> Implement supporting of DIsplay Name Generator https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator

I think the allure-junit-platform module already supports `@DisplayNameGeneration` - https://github.com/allure-framework/allure-java/blob/master/allure-junit-platform/src/main/java/io/qameta/allure/junitplatform/AllureJunitPlatform.java#L493 
The name of the test to display is obtained from the `org.junit.platform.launcher.TestIdentifier` entity where field `displayName` is affected by the selected `@DisplayNameGeneration`, right?

I tried to write some tests like in the - https://junit.org/junit5/docs/current/user-guide/#writing-tests-display-name-generator

```java
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

public class DisplayNameGenerationSupport {

    @Nested
    @DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
    class ReplaceUnderscoresGeneratorSupportTest {

        @Test
        void is_there_any_underscores() {
        }
    }

    @Nested
    @DisplayNameGeneration(DisplayNameGenerator.Simple.class)
    class SimpleNameGeneratorSupportTest {

        @Test
        void is_there_any_brackets() {
        }
    }

    @Nested
    @IndicativeSentencesGeneration(separator = " -> ", generator = DisplayNameGenerator.ReplaceUnderscores.class)
    class IndicativeSentencesGeneratorSupportTest {

        @Test
        void is_there_any_underscores() {
        }

        @ParameterizedTest(name = "argument is {0}")
        @ValueSource(ints = { 2016, 2020, 2048 })
        void is_there_any_underscores(int year) {
        }
    }

}
```

Then name is generated in accordance with the specified generator, which generally coincides with the result described on the junit5 guide page.
<img width="576" alt="DisplayNameGeneratorSupport" src="https://github.com/allure-framework/allure-java/assets/89605031/5f7469fa-6552-488e-9dba-999b0bf3c24a">

Maybe I'm missing something or do you have more information about what's missing here?
