### ISSUE TITLE
allure steps not included in the report with Cucumber and TestNg

### ISSUE THREAD

**Issue by VitalyShalaev** [allure-framework/allure-java#923]
Allure steps  with annotation "io.qameta.allure.Step" not included in the report with Cucumber and TestNg.
In pom I use dependencies:

<dependency>
   <groupId>io.cucumber</groupId>
   <artifactId>cucumber-java</artifactId>
   <version>5.7.0</version>
</dependency>
<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-testng</artifactId>
    <version>5.7.0</version>
</dependency>
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>7.8.0</version>
</dependency>
 <dependency>
     <groupId>io.qameta.allure</groupId>
     <artifactId>allure-cucumber5-jvm</artifactId>
     <version>2.22.1</version>
 </dependency>
....
<plugin>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-maven</artifactId>
    <version>2.12.0</version>
    <configuration>
        <reportVersion>2.22.1</reportVersion>
    </configuration>
</plugin>

If steps looks like that:

@When("Cucumber step")
public void cucumberStep() {
    allureStep();
}
@Step("This is AllureStep")
public void allureStep() {
    allureSubStep();
}
@Step("This is SubStep")
public void allureSubStep() {
    Allure.step("Allure InnerStep", () ->
            Allure.addAttachment("Attachment Name", "Content"));
}

Report looks:
![image](https://github.com/allure-framework/allure-java/assets/43988977/5af75be8-07ae-4821-97d3-179925d7c3e7)

But it should look like this:

![image](https://github.com/allure-framework/allure-java/assets/43988977/3a20cf03-748c-434a-8bf4-999b6110f708)

**Comment by baev** [comment]
You need to configure AspectJ in order to enable `@Step` and `@Attachment` annotations support. Under the hood, they are actually the same as calling `Allure.step` and `Allure.addAttachment` APIs.

**Comment by VitalyShalaev** [comment]
@baev Could you suggest me how to do this?
I am using the standard setting from the documentation:
`            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <includes>
                        <include>**/RunCucumberTest.java</include>
                    </includes>
                    <systemPropertyVariables>
                        <testFailureIgnore>false</testFailureIgnore>
                        <argLine>
                            -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                            -Dcucumber.options="--plugin io.qameta.allure.cucumber5jvm.AllureCucumber5Jvm"
                            -Dcucumber.options="--add-plugin io.qase.cucumber5.QaseEventListener"
                        </argLine>
                    </systemPropertyVariables>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>`
After adding to aop-ajc.xml <aspect name="io.qameta.allure.aspects.StepsAspects"/> the report did not change, StepsAspects Pointcuts were missing in the logs.

In the end, I copied the StepsAspects class into my project and it seems to work. Pointcuts  appeared in the logs.

**Comment by a-simeshin** [comment]
@VitalyShalaev 
> After adding to aop-ajc.xml the report did not change, StepsAspects Pointcuts were missing in the logs.
> In the end, I copied the StepsAspects class into my project and it seems to work. Pointcuts appeared in the logs.

This happens because the `aop-ajc.xml` file is missing from all of the above dependencies. In your case `aop-ajc.xml` or TestNG bundled in `allure-testng` dependency. 
To fix without moving the code and additional files, you need to check that your project contains `allure-java-commons` (bundled with `allure-cucumber5-jvm`) and `allure-testng`.

**Comment by VitalyShalaev** [comment]
@a-simeshin 
If I use the allure-testng dependency along with allure-cucumber5-jvm, then the tests in the allure report will start to be duplicated.

**Comment by ranjeetsinghsaluja** [comment]
@VitalyShalaev use this dependency allure-junit4 this will not duplicate but will show the steps. It is working for me fine

**Comment by ranjeetsinghsaluja** [comment]
@baev when used hybrid framework (TestNG+Cucumber) it does not work I have tried that but when I used Allure-Junit dependency it works and does not duplicate.

**Comment by VitalyShalaev** [comment]
@baev fix https://github.com/allure-framework/allure-java/pull/940 did not help, tested on 2.24.0.
