### ISSUE TITLE
🐞: Supported source version 'RELEASE_8' from annotation processor ... less than -source 11

### ISSUE THREAD

**Issue by rPraml** [allure-framework/allure-java#929]
### What happened?

Hello, we have an issue with the https://github.com/allure-framework/allure-java/blob/master/allure-descriptions-javadoc/src/main/java/io/qameta/allure/description/JavaDocDescriptionsProcessor.java#L48.

During compilation, the processor produces a warning. As we want to use `-Werror` as compile flag, (=Terminate compilation if warnings occur) exactly that happens, when the JavaDocDescriptionsProcessor is used.

I found an article on SO

https://stackoverflow.com/questions/8185331/forward-compatible-java-6-annotation-processor-and-supportedsourceversion

It is recommended to implement a
```java
   public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latest();
    }
```
instead of using the annotation `@SupportedSourceVersion(SourceVersion.RELEASE_8)`

Maybe you can think about this to change in further version?

Roland

### What Allure Integration are you using?

allure-descriptions-javadoc

### What version of Allure Integration you are using?

2.22.1

### What version of Allure Report you are using?

2.22.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
PR is welcome!
