### ISSUE TITLE
🐞: @Steps not working when with Quarkus/JUnit5

### ISSUE THREAD

**Issue by NirGrotel** [allure-framework/allure-java#932]
### What happened?

My infra is working with JUnit5 and Quarkus.
i have created some api tests and i added @Step to methods used in the test.
unfortunately I don't get the steps in the report.

do you guys know what I can do about it?

### What Allure Integration are you using?

allure-junit5

### What version of Allure Integration you are using?

2.14.0

### What version of Allure Report you are using?

2.10.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
Duplicate of https://github.com/allure-framework/allure2/issues/1428

**Comment by baev** [comment]
https://github.com/allure-framework/allure2/issues/1428#issuecomment-1920149626
