### ISSUE TITLE
🐞: [allure-karate] Don't save historyId

### ISSUE THREAD

**Issue by diogogt** [allure-framework/allure-java#938]
### What happened?

I'd like to use allure-karate but it doesn't save historyId and I can't control history on allure-report.
I saw on `AllureKarate.java` on beforeScenario it doesn't set the historyId.
I made a local change just to validate and be able to save the historics temporarily.
In the AllureKarate.java class on **beforeScenario** I added
`         String historyId = md5(scenarioName);`
And then
`         .setHistoryId(historyId)`

### What Allure Integration are you using?

allure-karate

### What version of Allure Integration you are using?

2.23.0

### What version of Allure Report you are using?

2.23.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thosni21** [comment]
**Temporarily  solution :** 

```
public CustomAllureKarate() {
    super();
}

@Override
public boolean beforeScenario(ScenarioRuntime sr) {
    boolean result = super.beforeScenario(sr);

    try {
        Field lifecycleField = AllureKarate.class.getDeclaredField("lifecycle");
        lifecycleField.setAccessible(true);
        AllureLifecycle lifecycle = (AllureLifecycle) lifecycleField.get(this);

        String scenarioName = sr.scenario.getName();
        String historyId = md5(scenarioName);

        lifecycle.updateTestCase(testResult -> testResult.setHistoryId(historyId));
    } catch (NoSuchFieldException | IllegalAccessException e) {
        e.printStackTrace();
    }

    return result;
}

private String md5(String input) {
    try {
        MessageDigest md = MessageDigest.getInstance("MD5");
        byte[] messageDigest = md.digest(input.getBytes());
        BigInteger no = new BigInteger(1, messageDigest);
        String hashText = no.toString(16);
        while (hashText.length() < 32) {
            hashText = "0" + hashText;
        }
        return hashText;
    } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException(e);
    }
}

```
