### ISSUE TITLE
readme.md should also have a section for Cucumber🐞: 

### ISSUE THREAD

**Issue by neerajaggarwal2501** [allure-framework/allure-java#954]
### What happened?

Open  "https://github.com/allure-framework/allure-java"
Scrloll down till you see README.md->Allure Java Integrations

Here , the maven dependency for below are mentioned
TestNG,JUnit 4,JUnit 5,Selenide,Rest Assured,OkHttp,gRPC,Http client,Http client 5,JAX-RS Filter,JsonUnit,Awaitility

I am exploring Allure Java Reports for Cucumber framework. In above we should also have Cucumber dependency listed.

for e.g.
Cucumber
<dependency>
   <groupId>io.qameta.allure</groupId>
    <artifactId>allure-cucumber7-jvm</artifactId>
   <version>$LATEST_VERSION</version>
</dependency>
![Allure](https://github.com/allure-framework/allure-java/assets/52820931/f75bc21d-399c-4c17-877b-c6a63b4bab4c)

### What Allure Integration are you using?

allure-cucumber7-jvm

### What version of Allure Integration you are using?

2.24.0

### What version of Allure Report you are using?

2.24.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PavelMal** [comment]
Hello @neerajaggarwal2501 
Added PR with cucumber section

**Comment by neerajaggarwal2501** [comment]
> Hello @neerajaggarwal2501 Added PR with cucumber section

Hello @PavelMal  Thanks.
