### ISSUE TITLE
🐞:  No execution info when running tests via JUnit5 Launcher API

### ISSUE THREAD

**Issue by wazzeps** [allure-framework/allure-java#979]
### What happened?

When running tests via the Launcher API

```
LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
    .selectors(selector)
    .build();

Launcher launcher = LauncherFactory.create();

launcher.execute(request);
```
execution info is empty:

![image](https://github.com/allure-framework/allure-java/assets/120301053/9ff45e27-4332-4cdd-aba1-9307f8c522bf)

Attachments are not cloned into the results folder and Allure-results files contain only basic information
`{"uuid":"2d1e446a-f232-47f6-a4af-5a3785e5d7d9","name":"Some test","children":["49bb1c84-dfeb-4b54-942b-9502455e899e"],"befores":[],"afters":[],"start":1701260685892,"stop":1701260697663}`

AspectJ configuration follows the [documentation ](https://allurereport.org/docs/junit5/#configure-aspectj).

### What Allure Integration are you using?

allure-junit5

### What version of Allure Integration you are using?

2.24.0

### What version of Allure Report you are using?

2.24.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
We actually do use Launcher API in our tests and everything works with no issues. See https://github.com/allure-framework/allure-java/blob/master/allure-junit5/src/test/java/io/qameta/allure/junit5/AllureJunit5Test.java#L417-L449

**Comment by baev** [comment]
> steps and attachments declared through annotations

`@Step` and `@Attachment` annotations rely on [AspectJ](https://allurereport.org/docs/junit5/#configure-aspectj). Make sure you have aspect weaver specified for the java process that runs the launcher.
