### ISSUE TITLE
🐞: Cucumber-JVM - Suite view : Cannot organize tests by parent-suite, suite and sub-suite 

### ISSUE THREAD

**Issue by harmin-parra** [allure-framework/allure-java#994]
### What happened?

I added the following annotations to my Cucumber-JVM test:

```
@allure.label.parentSuite:Cucumber
@allure.label.suite:Petstore
@allure.label.subSuite:CRUD
Feature: Petstore

  Scenario: Add a pet
    Given I have a pet store
    When I add a pet
    Then The pet is added
```

When I execute the test and generate the report, I don't get the expected suite hierarchy.

![image](https://github.com/allure-framework/allure-java/assets/16239820/0dfa5c43-65c0-4819-b201-96db279770d9)
 

### What Allure Integration are you using?

allure-cucumber7-jvm

### What version of Allure Integration you are using?

2.25.0

### What version of Allure Report you are using?

2.25.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by baev** [comment]
fixed by https://github.com/allure-framework/allure2/pull/2326

Will be released as 2.27.0 soon
